### ISSUE TITLE
Custodes: 9th Edition Codex Progress Tracker

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#10786]
## Beta Testing Import URL (Only do if you know what you're doing!)
https://raw.githubusercontent.com/BSData/wh40k/Custodes/9e/Imperium%20-%20Adeptus%20Custodes.cat

### Battle Forged Rules
- [x] Detachment Abilities
- [x] Shield Hosts
- [x] Shield Host Warlord Traits
- [x] Shield Host Relics
- [x] Stratagems/WLT/Relic Logic
- [x] Captain Commander
- [x] Shield Host Fighting Styles

### Army Rules
- [x] Warlord Traits
- [x] Relics of Terra
- [x] Relics of the Vigil

### Datasheets
- [x] Martial Ka'tah
- [x] Trajaan Valoris
- [x] Shield-Captain
- [x] Shield-Captain in Allarus Terminator Armour
- [x] Shield Captain on Dawneagle Jetbike
- [x] Blade Champion
- [x] Valerian
- [x] Aleya
- [x] Knight Centrua
- [x] Custodian Guard
- [x] Prosecutors
- [x] Custodian Wardens
- [x] Allarus Custodians
- [x] Vexilus Praetor
- [x] Vexilus Praetor in Allarus Terminator Armour
- [x] Venerable Contemptor Dreadnought
- [x] Vigilators
- [x] Vertus Praetors
- [x] Witchseekers
- [x] Venerable Land Raider
- [x] Anathema Psykana Rhino

### Misc
- [x] Add WLT/Relic entries to sisters characters and custodes characters
- [x] Emperor's Legion Limitations
- [x] Publication check
- [x] Link cleanup

**Comment by Blacob80** [comment]
~~Not sure if this is the right place to put this but misericordias are currently free on saggitarum.~~

**Comment by Muck1ng** [comment]
~~When Selecting a non Special Character and giving it "Emperors Heroes" Strat "Victor of the bloodgames" is not available Blood games does not need your char to be the Warlord to trigger, it just needs to have a warlord trait.~~ 

This is already fixed, redownload your data.

**Comment by Isphera** [comment]
~~Apologies if this is wrong place to put in issues that are spotted in the beta version, but it seems The Emperor's Heroes strategem is not giving Aleya her fixed Warlord Trait (Oblivion Knight) when selected. This is in both Adeptus Custodes and Anathema Psykana detachments.~~

Fixed, reimport the data.

**Comment by suburbjedi** [comment]
It appears the Guardian spears shooting profile is the same as the melee profile.

**Comment by Technoblazed** [comment]
All issues in this thread are fixed and it's merged to master for next week's release - please use standard bug reporting from now on.
