### ISSUE TITLE
MFM BONANZA

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#10836]
- [x] MFM Space Marines
- [x] MFM Ultramarines
- [x] MFM White Scars
- [x] MFM Iron Hands
- [x] MFM BT
- [x] MFM Salamanders
- [x] MFM RG
- [x] MFM BA
- [x] MFM DA
- [x] MFM SW
- [x] MFM DW
- [x] MFM GK
- [x] MFM SoS
- [x] MFM AC
- [x] MFM Sororitas (No changes)
- [x] MFM Assassins (No changes)
- [x] MFM AM
- [x] MFM AdMech
- [x] MFM IK
- [x] MFM Inquis (No changes)
- [x] MFM CSM
- [x] MFM DG
- [x] MFM TS (no changes)
- [x] MFM Daemons
- [x] MFM Chaos Knights
- [x] MFM Craftworlds
- [x] MFM Drukhari
- [x] MFM Quins
- [x] MFM Ynnari
- [x] MFM Necrons
- [x] MFM Orks
- [x] MFM T'au
- [x] MFM Nids
- [x] MFM GSC (Assumed no changes from Codex)
- [x] MFM Fortifications
- [x] MFM FW SM
- [x] MFM FW GK
- [x] MFM FW AM
- [x] MFM FW Inquis
- [x] MFM FW AC
- [x] MFM FW AdMech
- [x] MFM FW IK
- [x] MFM FW Titan Legions (No Changes)
- [x] MFM FW CSM
- [x] MFM FW DG
- [x] MFM FW CD
- [x] MFM FW CK
- [x] MFM FW CTL
- [x] MFM FW Craftworlds
- [x] MFM FW Drukhari
- [x] MFM FW Necrons
- [x] MFM FW Orks
- [x] MFM FW T'au
- [x] MFM FW Nids
- [x] MFM FW MISC

**Comment by blipper** [comment]
#10850 does MFM DA I think?

**Comment by FarseerVeraenthis** [comment]
> #10850 does MFM DA I think?

It certainly does some of it, I've not checked it out yet but might get to it tonight :+1:

**Comment by aaaronlucas** [comment]
#10867 should cover MFM Orks and MFM FW Orks
