### ISSUE TITLE
T'au Empire 9th Edition - Progress Tracker

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#10837]
## Import URL
https://raw.githubusercontent.com/BSData/wh40k/Tau/9e/T'au%20Empire.cat

### Battle-Forged Rules
- [x] Detachment Abilities
- [x] Septs
- [x] Stratagems
- [x] Prototype Systems

### Army Rules
- [x] Warlord Traits
- [x] Relics
- [x] Invocations of the Ethereals

### Matched Play Rules
- [x] Matches Play Rules

### Datasheets
- [x] Drones
- [x] Commander Shadowsun
- [x] Commander Farsight
- [x] Commander in Crisis Battlesuit
- [x] Commander in Enforcer Battlesuit
- [x] Commander in Coldstar Battlesuit
- [x] Cadre Fireblade
- [x] Kroot Shaper
- [x] Ethereal
- [x] Aun'va
- [x] Aun'shi
- [x] Darkstrider
- [x] Longstrike
- [x] Strike Team
- [x] Breacher Team
- [x] Kroot Carnivores
- [x] Krootox Riders
- [x] Crisis Battlesuits
- [x] Crisis Bodyguards
- [x] Stealth Battlesuits
- [x] Ghostkeel Battlesuit
- [x] Firesight Marksman
- [x] Tactical Drones
- [x] Pathfinder Team
- [x] Pirahnas
- [x] Vespid Stingwings
- [x] Kroot Hounds
- [x] Broadside Battlesuits
- [x] Riptide Battlesuit
- [x] Hammerhead Gunship
- [x] Sky Ray Gunship
- [x] Devilfish
- [x] Razorshark Strike Fighter
- [x] Sun Shark Bomber
- [x] Tidewall Shieldline
- [x] Tidewall Droneport
- [x] Tidewall Gunrig
- [x] Stormsurge

### Misc.
- [x] Points Values
- [x] Publication Check

**Comment by serahl** [comment]
Just wanted to wish you good luck with the new increasing point costs per number of the same weapon for Crisis Suits and Commanders! Looks like a lot of work to me :/

**Comment by Vailex** [comment]
- [x] AFP should be 24" not 18"
- [x] Stormsurge, should be able to replace its velocity tracker with counterfire defense system
- [ ] ~~Riptide, I believe the max is 1 support system~~ - nope, still 3

**Comment by Saionyde** [comment]
* [x] Fourth sentence in Fire Marker lights has  "this" misspelled ` If htis action is successfully `
* [x] Text in Drone Familiar Cluster - Spelling error "wound rol"

**Comment by K1r13y** [comment]
- [x] Aun'shi - cannot add invocations

**Comment by Nicktoms** [comment]
Piranhas weapons got mixed weapon profiles. Burst Cannons and Fusion blasters belongs to one another.

**Comment by KarakkTenivan** [comment]
Crisis Bodyguards can take an Iridium Suit on both the Shas'vre and a Shas'ui. They're only supposed to be able to take 1, and they cannot take 2 if they're both on Shas'ui.

**Comment by RhysAy** [comment]
- [x] Crisis Bodyguards can only take two drones when in their default configuration (They should be able to take 4, 2 for each model.)

**Comment by KarakkTenivan** [comment]
- [x] Broadside suits can take an extra Seeker Missile for free.

**Comment by Naturalnuke** [comment]
- [x] Dal'yth Sept Relic 'Dynamic Mirror Field' description is the Dal'yth Tenet

**Comment by Kahunaloa** [comment]
No lantern or resonator warhead prototype systems.

~~Bodyguards only have 3 hard points total should be 4. ( actually this one is unconfirmed)~~

**Comment by Saionyde** [comment]
* [x] Crisis Bodyguards are missing the Infantry Keyword
* [x] Cadre Fireblade missing Fireblade Pulse Rifle stats

**Comment by Vailex** [comment]
- [x] In the markerlight rule it says "One of more" it should say "One or more"
- [x] Broadsides should be 8 wounds per.  3 attacks stock and 4 attacks for sgt.  ld 8/9

**Comment by ghost** [comment]
- [x]  Farsight enclaves warlord trait improves AP by 3, not by 1

- [x] Relic missing-solid image projection unit.

**Comment by OumiKX139** [comment]
Less of a bug, more of convenience / visual clarity suggestion
When selecting Crisis / Commander wargear, can the weapons be sorted alphabetically, followed by all the zero cost wargear, sorted alphabetically, rather than mixed together in order?

**Comment by Vailex** [comment]
- [x] spelling bug for the BATTLESUIT rule. "subtract 1 from the hit rolls hwen resolving"  should be spelled "when"

**Comment by Nicktoms** [comment]
- [x] Enforcer Commanders have a 2+ save ~~and should be able to take drones as additional wargear.~~
- [x] If you choose a Bork'an detachment you can't select Aun'va.
- [x] Stealth Battlesuits have the old Camouflage Fields Description instead of the new.

**Comment by guygrrr** [comment]
Thanks for the awesome work on this! I've discovered a couple things you may want to take a look at. 

-Guardian Drones say Wound rolls of 1-3 don't work, I was under the impression it was Wound rolls of 1-2.
-In Dal'yth Sept it will not let me select Aun'Va as HQ
-Had a bug where Battlescribe crashed when I tried to duplicate a Fire Warrior Squad with one Guardian Drone and one markerlight, however I was unable to replicate it, maybe it was nothing.

**Comment by Rhysith** [comment]
- [x] Serene Unifier (Aun'Shi)- references Aun'Va in the ability rather than Aun'Shi. 
![image](https://user-images.githubusercontent.com/98373244/150909700-e503a279-6d8c-40cf-aa4c-888430b68623.png)

- [x] Aun'Shi is missing his special Honour Blade, "Fidelity" which is +2S, -2AP, 2D and exploding 6s to hit.

- [ ] ~~Not sure if there is anything you can do about this because of the individual points costs, but when selecting a Prototype System that replaces a chosen weapon, it continues to list the "replaced" item in the list and datasheet.~~
![image](https://user-images.githubusercontent.com/98373244/150916169-da6f18c5-c470-4e1d-a98f-b6f9c22acc90.png)
![image](https://user-images.githubusercontent.com/98373244/150916280-da23aeeb-4a30-413e-b905-73293a6b6872.png)

**Comment by Vailex** [comment]
- [x] Multi-Sensory Discouragement Array - should be a roll of 3D6 not 2D6

**Comment by Vailex** [comment]
- [x] Ghostkeel Stealth Field Generator - replace  "cclosest" with "closest" in the description

**Comment by Nicktoms** [comment]
- [ ] ~~Stealth Battlesuits - The unit has the Manta Strike ability and in the leak they didn't have that entry.~~

**Comment by serahl** [comment]
- [x] The ability "Ambushing Predators" for Kroot has a typo: "...first battle round, **model sin** this unit..."
- [x] The Farsight Enclaves Warlord Trait "Master of the Killing Blow" has a typo: "...The model that **attach** is allocated to cannot use..."
- [x] The "Stimm Injectors" prototype has a typo: "...the bearer can use this Prototype **SDystem**. **if** it does, ...""

**Comment by RhysAy** [comment]
- [x] If you try to take more Kroot Hound/Krootox/Shaper units than Kroot Carnivores a validation error is produced even if you select them from the elite/hq/fast attack slots and that limitation should only apply to the No Force Org slot.

**Comment by Prince-in-yellow** [comment]
How do we add this to our apps?

**Comment by RhysAy** [comment]
- [x] You are unable to select Allied Worlds Septs for the main septs, this is mainly important for an Allied FSE Sept as they keep the sept tenet, stratagem and warlord trait but are able to take ethereals (and cannot take a second commander per detachment).

**Comment by serahl** [comment]
- [x] The extra Sub-Weapons for the Stormsurge are wrong, it can take Twin Burst Cannons or Twin Airburst Projectors. Both only cost 5 points for the Stormsurge.

**Comment by Alex-40k** [comment]
The price of the third burst cannon in the crisis is wrong, it's currently 5, it should be 20

**Comment by Vailex** [comment]
- [x] HYMP are 30" range no longer 36"
- [x] Advanced Targeting System for the Broadsides should be free

**Comment by Vailex** [comment]
- [x] Riptide's Overcharged Ion Accelerator profile strength should be 8 not 9

**Comment by MatteoCesari78** [comment]
multiple stats of the riptide are wrong, BS should be 4,5,6, attacks should be 6,5,4, leadership should be 9

**Comment by serahl** [comment]
For some weird reason, the wargear for Crisis Bodyguards has different rules than the rest:

- [ ] Early warning override does not give them free Overwatch once per turn
- [ ] The Multi Tracker scores 2 additional hits on a hit roll of 6.

Not going to fix these as it's blatantly wrong and the rest are the same across the codex. The MT also makes no sense because they're max 1 per model, which makes no sense. -T

**Comment by MatteoCesari78** [comment]
i am not able atm to take the prototype burst cannon with a crisis sgt but reading the codex that should be possible

**Comment by Mad-Spy** [comment]
Piranha burst cannon is misspelled as "pirahna"

Same misspelling is also in "Drone Dock" and "Explodes" abilities for Piranhas.
