### ISSUE TITLE
Codex: Aeldari - Update

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#11002]
- [x] Initial data update
- [x] Storm Guardians are 70pts for 10, although they cost 8 per model
- [x] Dire Avengers are 55 for 5, although they cost 12 per model. Are these not updated yet? Options look like 8th edition to me.
 - Note: the points are now updated, along with the rest of the entry, even the Exarch powers work correctly :-)
- [x] Wraithlord is in the Heavy Support section, although it was moved to Elite
- [x] Autarch with Wings cannot be build properly. Good idea to implement it via checkmark, but it afterwards has two errors, that Death Spinner and Star Glaive are still selected. De-selecting Star Glaive to None works as intended (removes that error message), but removing the Pistol Replacment (Death Spinner in this case) and setting it to None raises a new error "Autarch must have 1 more selections of Death Spinner (minimum 1 each)." This is doubly wrong. 1st the category is not Deathspinner, but instead Pistol/Gun or whatever, 2nd there should be no error since the Fusion Pistol is already selected via the checkmark selection.
- [x] Vyper should be 5pts more expensive if it comes with the Shuriken Cannon.
- [x] Shining Spear Exarch has two errors. 1st he can change his Twin Shuriken Catapult to a TWIN Shuriken Cannon (should only be a single Cannon, not Twin), and 2nd changing it to the Cannon leads to an error message, that he has to have "1 more selections of Twin Shuriken Catapult (minimum 1 each)".
- [x] Same goes with changing his Laser Lance to a Star Lance. Seems like a lot of gear changes do not recognize that an alternative has been chosen.
- [x] Not sure if this is an error, so bare with me here for a moment: Rangers have a rule that says "For every 5 models in this unit, one Ranger can be equipped [...]". Currently it is implemented that you can take 2 versions of equipment as soon as there are 6 models in this unit. I guess it is so that this should only be able when there are iterations of 5 models, but I might be wrong here. Just noticed you implemented it for the Storm Guardian as I am interpreting the rule, so there are 2 ways you have done it currently. It should at least be consistent.
- [x] Banshee Exarch cannot select Exarch powers. Any reason that the "normal" Banshees are listed individually? On all other infantry units these are grouped up. And since there is no possibility to equip them with different stuff, I would prefer it here as well.
- [x] Are there any plans doing the stat changes if chosing an Exarch power? Because in that case the Exarch gains one wound and all instead of DA gain either an additional Attack or get their BS increased by 1. This is not reflected currently.
- [x] Warlock units of all kind (foot, skyrunner, single, multi, slot, slotless) are missing the Psykic table (number of casts, denies and from which table to select the power(s) from).
- [x] Swooping Hawk Exarch suffers from the issue mentioned above that an error message is raised, if he switches his Lasblaster for a Hawk's Talon. 
  - [x] Additionally, he is able to pick the Swooping Hawk relic although the Stratagem is not chosen (it is not even implemented yet).
- [x] Same goes for the Dark Reapers Exarch, he can also pick it's Exarch relic for free.
- [x] Windriders with Scatter Lasers are 5pts too cheap, they cost 25 instead of 20.
- [x] Fire Prism is 5pts too cheap if equipped with a Shuriken Cannon instead of the Twin Catapults (no cost currently for that but it should be 5). Same is true for the Night Spinner and the Falcon, I just realized. Aaand for the Wave Serpent, although there it should be +10 points, not only +5 like for the other 3 tanks.
- [x] The Support Weapons Shadow Weaver option is too expensive, it only costs 45 (so the base), not 45 + 20.
- [x] Warp Spiders are missing!!

##Typos:

- [x] Avatar of Khaine: The Bloody-Handed (Aura) ability: "[...] you can re-roll charge rols made for that unit."

##Other stuff:

- [x] Wouldn't say this is a bug, but at least want to post it here as a topic of discussion: Shouldn't units be coming with the cheapest loadout as standard? Currently for example the War Walker (65 points) could be already taken for 55 points if both Shuriken Cannons are replaced with Scatter Lasers. Same for the Falcon (145 points) that could switch its Cannon for a Laser (down to 140). I guess this would be preferable for list building. Additionally, in case of the Falcon the Scatter Laser is the default loadout. Strangely the Cannons are "correct" for the War Walkers.
   - Generally, we follow the default load-out as listed in the book. In this case, the Falcon is unusual as it is the only tank in the book that comes with Scatter Lasers as the defaut load-out. As such, the heavy weapon selection pulls from the same selection list as the other units, which defaults to Shuriken Cannon - since that is the default load-out for other units that use this list. It is a quirk of BS that the default cannot be changed, hence the Falcon will continue to be "unusual" due to this quirk

- [x] No possibility to choose special weapons (harlequin's kiss, caress or embrace) on a harlequin player with a fusion pistol (troop)
- [ ] Asuryani - Missing "Champion of The Aeldari" Stratagem as pre-game choice
- [x] Harlequins - Missing "Champion of The Aeldari" Stratagem as pre-game choice
- [x] Missing "Favoured of The Laughing God" Stratagem as pre-game choice
- [x] Harlequins - Treasures of the Aeldari stratagem is not working properly
- [ ] Asuryani - Treasures of the Aeldari stratagem is not working properly

**Comment by buckeyede06** [comment]
I have almost all of the data sheets, rules, images and point costs from all the leaks. If that helps. They are blurry though so not sure if that helps you….

**Comment by FarseerVeraenthis** [comment]
> I have almost all of the data sheets, rules, images and point costs from all the leaks. If that helps. They are blurry though so not sure if that helps you….

Thanks for the offer but I have them already, and I've pre-ordered the codex from my FLGS so hopefully I'll get that a few days early too - I had Eldritch Omens on Thursday afternoon 😉

**Comment by FarseerVeraenthis** [comment]
I am getting there... if you're following this progress tracker note that your list will need to rebuilt from the ground up. Therefore, if you have any Army Lists you're keeping for historical purposes - make sure you have a PDF copy so it doesn't get broken when you open it with the new CAT file (when it gets released...)!!!!

**Comment by GrimlockZ** [comment]
Thank you for your work

**Comment by William-Barry** [comment]
Fantastic stuff. If you need someone to test Harlies let me know. Can't wait for the official drop (my local version is just enough to see what I want).

**Comment by FarseerVeraenthis** [comment]
If you're handy with GitHub, you can get the latest version of the CAT using the branch NewAeldariCodex :smile: 
Note: there are known issues with this file as currently presented, it is still WIP :+1:

**Comment by anchoress47** [comment]
Hey, thank you for all the work you've done already! Will test your data with some new Rosters and write down in here all stuff that I can find. Please don't mind my wording too much, I'm no native speaker and don't want to sound harsh in any way. Just trying to explain (what i think are) errors as thoroughly as i can. If i may come over as rude, this is not my intention at all. Thanks for all the work you have put into it already, really!

- Storm Guardians are 70pts for 10, although they cost 8 per model
- Dire Avengers are 55 for 5, although they cost 12 per model. Are these not updated yet? Options look like 8th edition to me.
- Wraithlord is in the Heavy Support section, although it was moved to Elite
- Autarch with Wings cannot be build properly. Good idea to implement it via checkmark, but it afterwards has two errors, that Death Spinner and Star Glaive are still selected. De-selecting Star Glaive to None works as intended (removes that error message), but removing the Pistol Replacment (Death Spinner in this case) and setting it to None raises a new error "Autarch must have 1 more selections of Death Spinner (minimum 1 each)." This is doubly wrong. 1st the category is not Deathspinner, but instead Pistol/Gun or whatever, 2nd there should be no error since the Fusion Pistol is already selected via the checkmark selection.
- Vyper should be 5pts more expensive if it comes with the Shuriken Cannon.
- Shining Spear Exarch has two errors. 1st he can change his Twin Shuriken Catapult to a TWIN Shuriken Cannon (should only be a single Cannon, not Twin), and 2nd changing it to the Cannon leads to an error message, that he has to have "1 more selections of Twin Shuriken Catapult (minimum 1 each)".
- Same goes with changing his Laser Lance to a Star Lance. Seems like a lot of gear changes do not recognize that an alternative has been chosen.
- Not sure if this is an error, so bare with me here for a moment: Rangers have a rule that says "For every 5 models in this unit, one Ranger can be equipped [...]". Currently it is implemented that you can take 2 versions of equipment as soon as there are 6 models in this unit. I guess it is so that this should only be able when there are iterations of 5 models, but I might be wrong here. Just noticed you implemented it for the Storm Guardian as I am interpreting the rule, so there are 2 ways you have done it currently. It should at least be consistent.
- Banshee Exarch cannot select Exarch powers. Any reason that the "normal" Banshees are listed individually? On all other infantry units these are grouped up. And since there is no possibility to equip them with different stuff, I would prefer it here as well.
- Are there any plans doing the stat changes if chosing an Exarch power? Because in that case the Exarch gains one wound and all instead of DA gain either an additional Attack or get their BS increased by 1. This is not reflected currently.
- Warlock units of all kind (foot, skyrunner, single, multi, slot, slotless) are missing the Psykic table (number of casts, denies and from which table to select the power(s) from).
- Swooping Hawk Exarch suffers from the issue mentioned above that an error message is raised, if he switches his Lasblaster for a Hawk's Talon. Additionally, he is able to pick the Swooping Hawk relic although the Stratagem is not chosen (it is not even implemented yet).
- Same goes for the Dark Reapers Exarch, he can also pick it's Exarch relic for free.
- Windriders with Scatter Lasers are 5pts too cheap, they cost 25 instead of 20.
- Fire Prism is 5pts too cheap if equipped with a Shuriken Cannon instead of the Twin Catapults (no cost currently for that but it should be 5). Same is true for the Night Spinner and the Falcon, I just realized. Aaand for the Wave Serpent, although there it should be +10 points, not only +5 like for the other 3 tanks.
- The Support Weapons Shadow Weaver option is too expensive, it only costs 45 (so the base), not 45 + 20.

Typos:
- Avatar of Khaine: The Bloody-Handed (Aura) ability: "[...] you can re-roll charge **_rols_** made for that unit."

Other stuff:
- Wouldn't say this is a bug, but at least want to post it here as a topic of discussion: Shouldn't units be coming with the cheapest loadout as standard? Currently for example the War Walker (65 points) could be already taken for 55 points if both Shuriken Cannons are replaced with Scatter Lasers. Same for the Falcon (145 points) that could switch its Cannon for a Laser (down to 140). I guess this would be preferable for list building. Additionally, in case of the Falcon the Scatter Laser is the default loadout. Strangely the Cannons are "correct" for the War Walkers.

**Comment by hatchetboy** [comment]
Amazing as ever!!

I can’t get the clown troops to equip properly. You should be able to independently select the melee upgrade and pistol upgrade. They way you’ve done it seems to limit to one or the other.  I.e. You should be able to do a clown with fusion/kiss.

**Comment by William-Barry** [comment]
Updates for Harlequins can be found here. [Harlequin Update](https://github.com/William-Barry/wh40k/tree/Harlequin-Suggestions)

- Resolved Troupes. Reviewing others
- Resolved Skyweaver Haywire Cannon

If anyone tests the main or mine, please let me know I can look at these for Harlies.

**Comment by William-Barry** [comment]
> I've branched off your and have some updates coming for the Harlies. Mainly the Troupes.

Updates for Harlequins can be found here. [Harlequin Update](https://github.com/William-Barry/wh40k/tree/Harlequin-Suggestions)

- Resolved Troupes. Reviewing others

**Comment by Youn-Atitd** [comment]
It appears you missed Warping Spiders.

**Comment by Tyrowski** [comment]
Thanks for your awesome work! 

Couple things for the Harlequin file: 

- No possibility to choose special weapons (harlequin's kiss, caress or embrace) on a harlequin player with a fusion pistol (troop) 
- Missing "Champion of The Aeldari" Stratagem as pre-game choice (p99 of the codex)
- Missing "Favoured of The Laughing God" Stratagem as pre-game choice 

Edit: Also The "Treasures of the Aeldari" stratagem can be used twice in a strike force game and 3 times in an onslaught game

**Comment by RespectableJack** [comment]
Thanks for all the great work!

- When I add one warlock via the Elites slot or No Force Org slot, if my HQ slots are filled, such as 3 in a battalion, it says I have too many HQs even though warlocks aren't even HQs
- When I add 2 warlocks via the Elites slot or No Force Org slot, if i have two HQs it says I have too many HQs selected even though they are elites or they do not take up a slot

**Comment by William-Barry** [comment]
> Thanks for your awesome work!
> 
> Couple things for the Harlequin file:
> 
> * No possibility to choose special weapons (harlequin's kiss, caress or embrace) on a harlequin player with a fusion pistol (troop)
> * Missing "Champion of The Aeldari" Stratagem as pre-game choice (p99 of the codex)
> * Missing "Favoured of The Laughing God" Stratagem as pre-game choice
> 
> Edit: Also The "Treasures of the Aeldari" stratagem can be used twice in a strike force game and 3 times in an onslaught game

You can check my fork/branch to see if the weapon profile is correct.

**Comment by comradegoode** [comment]
Thank you for doing all this work! I found a few mistakes

- The shuriken cannon seems to be missing from the heavy weapons list so you can't put them on a wraithlord, falcon, etc
- The wraithlord doesn't have an option for shuriken catapults, just the flamers
- The webway gate is still 95 points for me

**Comment by FarseerVeraenthis** [comment]
> Thank you for doing all this work! I found a few mistakes
> 
> * The shuriken cannon seems to be missing from the heavy weapons list so you can't put them on a wraithlord, falcon, etc
> * The wraithlord doesn't have an option for shuriken catapults, just the flamers
> * The webway gate is still 95 points for me

It sounds like you need to download the latest version of the Ynnari Library, as well as the latest GST :+1:

**Comment by georgemummert** [comment]
Minor Troupe issues I didn't see detailed previously:
- Leader Player in a Harlequins Troupe does not currently increase in points for adding a special weapon (Kiss or Aeldari Power Sword). 
- No option currently exists to provide the Lead Player with a Neuro Disruptor or Fusion Pistol.

**Comment by georgemummert** [comment]
@FarseerVeraenthis I haven't edited BattleScribe data before, but made a go of it tonight. To my own testing, I believe I resolved:
- all issues with Troupes and their special weapon limitations.
- some issues with the Saedath relics not being correctly locked to weapons (Twilight's Fang can only replace Aeldari Power Sword) or not being correctly locked to Saedaths (Shadow Stone can be selected in Saedaths other than Light)
- built out the mechanics behind Champion of the Aeldari and Favoured of the Laughing God strategems

As far as I'm concerned, my efforts tonight were all just pointless fun tinkering where I learned what I was doing on the fly, but it turns out I quite enjoyed it. I know you're like 98% of the way there with this monster of a codex, and I want to personally thank you for all of the work you've done. 

If it would in any way be helpful to have another set of hands involved, I'd love to get in contact with you and figure out a way to possibly contribute to some of this last-mile stuff or maybe some overall cleanup (lots of references to old codex pages, etc) that I know are going to be a bear to resolve in full.

**Comment by jsburns13** [comment]
@FarseerVeraenthis thanks so much for your work! I am no rules expert, but I think I've found a few bugs today that are not listed in this thread. Please let me know if I am just wrong about things.

Autarch Skyrunner - Laser Lance and Fusion Gun can be taken without any additional points; BS currently shows +5 and +10 respectively

Fire Dragons - looks like they still have their last point value of 18 ppm; they are 23 ppm in the new codex

Ghosthelm of Alishazier - does not allow for an additional selection from RoF. A Warlock with the relic doesn't gain access to the list, and a Farseer throws an error for having too many powers when adding an additional RoF.

Seer Council - Eldrad Ulthran does not have the "Seer Council" option (working fine for regular Farseers as far as I can tell)

**Comment by Shintome** [comment]
@FarseerVeraenthis Thank you for all your hard work! No idea what I'm doing here but I did notice a small detail that might throw someone off.

Rangers  - They do not have the Resonator Shard keyword needed for the Stratagem of the same name. 

Edit: Fixed my comment, sorry for any confusion.

**Comment by Shintome** [comment]
Another small bug, the error validation tool comes on whenever you try to take a replacement weapon relic on the Autarch Skyrunner. You need to have the Banshee blade to take either the Shard of Anaris or Firesabre but if you choose it and a relic the error pops up saying you need 0 of either option. 

Hopefully I explained that clearly but I can elaborate if you need it. Thanks again for everything!

**Comment by ghost** [comment]
Not sure if this has been brought to attention yet somewhere else but GW Backtracked officially on GW Community on the Autarch equipment choice.
