### ISSUE TITLE
Codex: Aeldari - Released Data Bug Hunt

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#11019]
# List Bugs Here Please!!
~~- [ ] Validation of mixed Ynnari Detachments is not incorporated~~ <-- Moved to new issue.
~~- [ ] Corsair validation & force build opportunities~~ <-- Moved to new issue.
~~- [ ] All the old legends options (which are still legal for Legends legal casual matches) are not available.~~ <-- Moved to new issue.
- [x] Characters have access to relics that they shouldn't have access to.
- [x] Relic validation needs checking with combined forces of Asuryani & Harlequins
- [x] Psytronome of Iyanden cannot be taken on autarch.
- [x] Troupe statline not showing when viewing list, only troupe leader statline is there.
- [x] Solitaire has s3 and t3 while it should be s4 and t4
- [x] Wraithseer lacks points on weapons.
- [x] Twin shuriken catapult is 12" instead of the new 18"
- [x] It currently lets you add multiple instances of Fuegan without generating an error that it has too many selections of the character.
- [x] Wraithseer is missing all psyker info including Spells Known, Casts, Denies, etc.
- [x] Craftworld attributes are still 8th edition.
- [x] Unable to add more than one warlock conclave to none force org charts.
- [x] Unable to add Champion of the Aeldari or Treasures of the Aeldari.
- [x] Most units do not have shurkian cannon options where they should have them.
- [x] Windriders Shurkian cannons not pointed correct.
- [x] Guardians defenders have no weapons.
- [x] Storm Guardians have no pistols.
- [x] Ghosthelm of Alishazier does not unlock runes of fortune, or if runes of fortune is already unlocked on a datasheet brings up an error stating too many powers.
- [x] Biel Tann relic doesn’t allow for an additional power.
- [x] Scattershield on Wraithknight says 5+ invulsave.. Its 4+
- [x] Aeldari flamer say $ in strength (typo)
- [x] The Webway Gate is listed as 95 points, rather than 80.
- [x] Shimmershields say 5+ when it should be 4+
- [x] In Ulthwes description PSYKER is misspelled as PYSKER.
- [x] Fire dragons are 18ppm when they should be 23.
- [x] Ynnari Warden of Souls WLT appears even without Ynnari being selected.
- [x] Wave serpent is missing its Serpent Shield. 
- [x] Corsair Voidreavers by default only have the Felarch in the unit when should have 4 Voidreavers.
- [x] The relic Talisman of Tionchar has a 5 pt cost on it.
- [x] Howling Banshee Earch power, Nerve-shredding Shriek has the typo "Howling Banshee Exarchand roll one D6"
- [x] Star Glaive still has the old profile (D3 damage and the -1 to hit with it ability)
- [x] Harlequin's Troupe are unable to take a special weapon and a special pistol (eg. caress and fusion)
- [x] Rangers still appear to have the old 3+ BS instead of the new 2+
- [x] Craftworld Eldar characters don't have the Champion of the Aeldari Selection Entry which would allow them to take an warlord trait.
- [x] Wave Serpent and Hemlock are missing the degradation table.
- [x] The Autarch Skyrunner is still half the old legends entry where he has weapon options, should be just 100pts flat with a laser lance and no weapon options anymore.
- [x] Fire Dragons should be 23 points. Flamer should be free. Firepike should be 10.
- [x] Spirit Stone and Ghosthelm are not allowing extra Psychic Powers from any the Psyker knows and Runes of Fortune respectively.
- [x] Seer council Strat gives a CP instead of removing
- [x] Fire Dragons have no weapon
- [x] Typo in Hand of Asuryan - Onjective Secured
- [x] Shuriken Weapons rule missing a full stop after 'Shuriken'
- [x] Relics of the Shrines gives 1CP instead of taking 1CP away, and Roster begins with "2 too many selections of Aspect Shrine Relic" when there aren't any.
- [x] Voidweaver needs to have Power Level input.
- [x] Eldrad cannot be selected as the target for Seer Council stratagem like other Farseers
- [x] If you choose 2 patrol detachtments 1 of them dont reduce the CP by 2
- [x] Patrol detachment with 2 Elite slots and 2 HQ slots, marked as error for having too much Elite and HQ slots
- [x] All pre-game stratagems add CP instead of reducing them
- [x] If you select the Twin Shuriken Catapult for a Shinning Spears Exarch, it marks as an error that he must have 1 cannon
- [x] Eldrad new Staff of Ulthamar and witchblade have an unique profile now and the damage is now 2 instead of D3
- [x] Striking Scorpions should have 3 attacks instead of 2
- [x] Striking Scorpions Exarch with exarch power should have 1 more attack
- [x] I’m unable to add any Altansar warlord traits so looks like they’re missing
- [x] Dukhari should have access to Corsair datasheets but do not currently. The Way Seeker is also missing its Witch staff
- [x] farseer don't have smite power showing in psychic power list
- [x] When selecting "Seer Council" stratagem, warlocks don't get the check box to select them as part of the council. Consequently the roster is tagged invalid with following error message: "must have 1 omre selections of seer council (Warlock Units) (minimum 1)
- [x] Just another thing I've noticed, Warlock units on foot don't have their PL increased over 3 when taken in bigger squads
- [x] Autarch howling banshee mask still has the Eldritch Omens statblock.
- [x] Ynnari warlord trait is still the old version from Phoenix rising
- [x] Warlock Skyrunners don't have a box to complete the Seer Council Stratagem integrity check.
- [x] When Adding an Exarch Power to a Unit, it should add +1 PL to the unit

**Comment by Pyrothenia** [comment]
Craftworld attributes are still 8th edition. 
Unable to add more than one warlock conclave to none force org charts.
Unable to add Champion of the Aeldari or Treasures of the Aeldari.
Most units do not have shurkian cannon options where they should have them.
Windriders Shurkian cannons not pointed correct. 
Guardians defenders have no weapons.
Storm Guardians have no pistols. 
Characters have access to relics that they shouldn't have access to. 
Ghosthelm of Alishazier does not unlock runes of fortune, or if runes of fortune is already unlocked on a datasheet brings up an error stating too many powers. 

Just a few i have seen so far.

**Comment by buckeyede06** [comment]
Bieltan relic doesn’t allow for an additional power.

**Comment by Ithyrrinaz** [comment]
Scattershield on Wraithknight says 5+ invulsave.. Its 4+
Aeldari flamer say $ in strength (typo)

**Comment by EcoWraith** [comment]
The Webway Gate is listed as 95 points, rather than 80. 

Regardless, thanks for getting this out so quickly 😁

**Comment by Limz1** [comment]
Typo: Shimmershields say 5+ when it should be 4+

**Comment by grimfang999** [comment]
Thank you for the work!

Typo: In Ulthwes description PSYKER is misspelled as PYSKER.
Points error: Fire dragons are 18ppm when they should be 23.
Additional minor: Ynnari Warden of Souls WLT appears even without Ynnari being selected.

**Comment by ForSuDor** [comment]
Missing: Wave serpent is missing its Serpent Shield.
Missing: Corsair Voidreavers by default only have the Felarch in the unit when should have 4 Voidreavers.
Points error: The relic Talisman of Tionchar has a 5 pt cost on it.
Typo: Howling Banshee Earch power, Nerve-shredding Shriek has the typo "Howling Banshee Exarchand roll one D6"
Typo: Star Glaive still has the old profile (D3 damage and the -1 to hit with it ability)

**Comment by MrDood1313** [comment]
Harlequin's Troupe are unable to take a special weapon and a special pistol (eg. caress and fusion)

**Comment by Leox926** [comment]
Typo: Rangers still appear to have the old 3+ BS instead of the new 2+

**Comment by paul31** [comment]
Harlequin Troupe should have additional options:
Fusion pistol + Caress
Fusion pistol + Embrace
Neuro Disruptor + Caress
Neuro Disruptor + Embrace

Also, thanks so much for all the hard work with this!!

**Comment by hieronymouse** [comment]
Craftworld Eldar characters don't have the Champion of the Aeldari Selection Entry which would allow them to take an warlord trait.

**Comment by hieronymouse** [comment]
More a quality of life issue:

Wave Serpent and Hemlock are missing the degradation table.

**Comment by Khadgast** [comment]
The Autarch Skyrunner is still half the old legends entry where he has weapon options, should be just 100pts flat with a laser lance and no weapon options anymore.

**Comment by Mad-Spy** [comment]
Copied from #11021 

Fire Dragons should be 23 points. Flamer should be free. Firepike should be 10.
Spirit Stone and Ghosthelm are not allowing extra Psychic Powers from any the Psyker knows and Runes of Fortune respectively.

**Comment by Mad-Spy** [comment]
Copied from #11020 

Seer council Strat gives a CP instead of removing

When you give the ulthwe relic for a psyckwr to gain an additional psychic power, BS registers an error that the psycker has too many powers when it should be allowed to have an additional power from Fortune only.

**Comment by Mad-Spy** [comment]
Fire Dragons have no weapon
Typo in Hand of Asuryan - **Onjective** Secured
Shuriken Weapons rule missing a full stop after 'Shuriken'

**Comment by hieronymouse** [comment]
Treasures of the Aeldari isn't allowing the "free" relic to be placed on a Craftworld character, and paying the CP for a Harlequin relic, where the Harlequin is the Warlord. 
![image](https://user-images.githubusercontent.com/23392644/156980259-953bdfcc-e742-4cdd-8ba5-bbdb5bb5557c.png)

![image](https://user-images.githubusercontent.com/23392644/156980192-dfa8584d-0f93-43e6-899f-eb75a99ece80.png)

**Comment by hieronymouse** [comment]
Relics of the Shrines gives 1CP instead of taking 1CP away, and Roster begins with "2 too many selections of Aspect Shrine Relic" when there aren't any. 

Potential (might break something else) Fix: Remove "decrement" condition in Aspect Shrine Relic Shared Selection Entry, insert condition group "and" under increment [max 0 selections in roster] by 2, insert condition "if equal to 0 selections of Treasures of the Aeldari Relic (shared) in Parent".

**Comment by hieronymouse** [comment]
Voidweaver needs to have Power Level input.

**Comment by marradius** [comment]
Eldrad cannot be selected as the target for Seer Council stratagem like other Farseers

**Comment by Katti27** [comment]
Correction for the Autarch Skyrunner bug identified above:
Autarch is equipped with a Laser Lance and can replace it with either 1 Dragon fusion gun OR 1 Banshee Blade (for no additional points).

**Comment by marradius** [comment]
· If you choose 2 patrol detachtments 1 of them dont reduce the CP by 2
· Patrol detachment with 2 Elite slots and 2 HQ slots, marked as error for having too much Elite and HQ slots
· All pre-game stratagems add CP instead of reducing them
· If you select the Twin Shuriken Catapult for a Shinning Spears Exarch, it marks as an error that he must have 1 cannon
· Eldrad new Staff of Ulthamar and witchblade have an unique profile now and the damage is now 2 instead of D3
· Striking Scorpions should have 3 attacks instead of 2
· Striking Scorpions Exarch with exarch power should have 1 more attack

**Comment by msgtquasar** [comment]
Thanks for al your work on this!

I’m unable to add any Altansar warlord traits so looks like they’re missing

**Comment by Someoneincheck** [comment]
Thank you for all the amazing work!

Dukhari should have access to Corsair datasheets but do not currently. The Way Seeker is also missing its Witch staff

Thanks!

**Comment by jimmyjohnny25** [comment]
farseer don't have smite power showing in psychic power list

**Comment by Giltharin** [comment]
When selecting "Seer Council" stratagem, warlocks don't get the check box to select them as part of the council. Consequently the roster is tagged invalid with following error message: "must have 1 omre selections of seer council (Warlock Units) (minimum 1)

**Comment by Kalruhan** [comment]
Thanks for your work!

Just another thing I've noticed, Warlock units on foot don't have their PL increased over 3 when taken in bigger squads

**Comment by Tyrowski** [comment]
Harlequins: 
Codex states it is possible to exchange a shuriken pistol in a troupe with a fusion pistol and neuro disruptor. This doesn't disallow to put one of the special weapons (like caress or embrace) on the same model 

in the current datafile release this is impossible to do, you can only put a fusion pistol on a model with a kiss

**Comment by MariusBP** [comment]
Craftworlds:
Autarch howling banshee mask still has the  Eldritch Omens statblock.
It should not give opponents -1A

**Comment by dWhisper** [comment]
When Adding an Exarch Power to a Unit, it should add +1 PL to the unit

**Comment by wendigo835** [comment]
- The Autarch Jump Generator does not change the unit table's speed characteristic from 7" to 12"
- Warlord is still an option in other datacards even after a warlord has been selected
- More a preference than a bug, but could the "Banshee Blade, Fusion Pistol, Mandiblasters..." option in the Autarch statblock turn invisible after selecting any other option?

**Comment by dWhisper** [comment]
Warlock Skyrunners in the no force org slot are using the 8e PL values

**Comment by NekuraIzou** [comment]
Harlequin Troupe are 4 Power Rating even when they go above 7 members when Power Rating should increase to 9.

**Comment by dWhisper** [comment]
> 

The PLs are correct for Shroud Runners and Autarchs. Both should be 5.

**Comment by Meface01** [comment]
Adding a scatter laser to one model adds it to all models in that unit (War walkers, Vypers, Multiple 
Guardian Heavy Weapons Platforms)

**Comment by FarseerVeraenthis** [comment]
> Thank you for all the amazing work!
> 
> Dukhari should have access to Corsair datasheets but do not currently. The Way Seeker is also missing its Witch staff
> 
> Thanks!

Corsair datasheets are currently held in the Aeldari CAT, hence if you wish to include some Corsairs in a Drukhari army you will have to add a child detachment to pull them in.
In time I might move the datasheet to the Ynnari Library but they'll stay in the Aeldari CAT for the moment.

**Comment by FarseerVeraenthis** [comment]
> When selecting "Seer Council" stratagem, warlocks don't get the check box to select them as part of the council. Consequently the roster is tagged invalid with following error message: "must have 1 omre selections of seer council (Warlock Units) (minimum 1)

Remember, you need two Warlocks in the uint in order for it to be a valid target for this Stratagem 😉

**Comment by ghost** [comment]
No Force Org Warlocks creates a nested unit of warlocks, each warlock added to the unit is a unit of warlocks that can have warlocks added to it

**Comment by kaintxu** [comment]
Autarch skyrunner is showing as 105 points while it should be 100 flat with lance.

**Comment by Eskeblaf** [comment]
Harlequins bugs:
Troupe statline not showing when viewing list, only troupe leader statline is there.
Solitaire has s3 and t3 while it should be s4 and t4.

**Comment by grimfang999** [comment]
Autarch star glaive is using the 8th edition profile

**Comment by Giltharin** [comment]
> 

I did not notice it. Thanks for the great job. Apologies for wrong report.

**Comment by RefinSoch** [comment]
Psytronome of Iyanden cannot be taken on autarch. In previous edition it was limited to psykers, but this limitation was removed in new codex.

**Comment by RazzorB** [comment]
banshee mask lost important part of the rule:
While an enemy unit is within Engagement Range of the bearer, **if the bearer's unit made a charge move this turn**, that enemy is not eligible to fight....
![изображение](https://user-images.githubusercontent.com/101185187/157231069-c45167b6-5017-4a74-b587-e67e0d929ed7.png)

**Comment by RazzorB** [comment]
old rules for scattershields and shimmershields for Dire Avengers Exarch, Shining spears exarch and Wraithknight. Now it gives 4++ invulnerable save to the **bearer**
![изображение](https://user-images.githubusercontent.com/101185187/157231747-101366a4-b93d-4620-a525-8ca98a9da691.png)
![изображение](https://user-images.githubusercontent.com/101185187/157231838-42c2356a-206a-4a4a-96d6-e364a9355a3c.png)

**Comment by K-hue-cell** [comment]
Altansar Warlord traits are missing.
Wraithseer lacks points on weapons.

**Comment by RorySmith9120** [comment]
Twin shuriken catapult is 12" instead of the new 18"

**Comment by Trowis** [comment]
Wraithlord missing support weapon options: Shuriken Catapult
These are default, data only shows (None) or Flamer, and throws an error unless Flamer is selected.

**Comment by dWhisper** [comment]
It currently lets you add multiple instances of Fuegan without generating an error that it has too many selections of the character.

**Comment by OddestFuture** [comment]
All the old legends options (which are still legal for Legends legal casual matches) are not available. This includes things like the old corsair range, the Bonesinger and certain Autarch Legends only builds.

**Comment by OddestFuture** [comment]
It seems referencing the data sheet vs the points page that the extra death spinner on the warp spider exarch should not cost points, only the powerblade should (which should be separate)

**Comment by FarseerVeraenthis** [comment]
> It seems referencing the data sheet vs the points page that the extra death spinner on the warp spider exarch should not cost points, only the powerblade should (which should be separate)

You don't get to choose whether you take powerblades or not. 
You can choose to be equipped with 1 additional Death Spinner AND 1 Powerblades.

**Comment by S0uLy-DaaN** [comment]
> > When selecting "Seer Council" stratagem, warlocks don't get the check box to select them as part of the council. Consequently the roster is tagged invalid with following error message: "must have 1 omre selections of seer council (Warlock Units) (minimum 1)
> 
> Remember, you need two Warlocks in the uint in order for it to be a valid target for this Stratagem 😉

It only works for Standart Warlocks, not for a Group of Warlock-Skyrunners, that have to been added as well because the Keywords are the same.

**Comment by crispyjello** [comment]
Is seems Wraithguard is missing War Construct (pg 165) unless I'm mistaken. I can't see it.
Thanks for the effort putting this together!

**Comment by FarseerVeraenthis** [comment]
> > > When selecting "Seer Council" stratagem, warlocks don't get the check box to select them as part of the council. Consequently the roster is tagged invalid with following error message: "must have 1 omre selections of seer council (Warlock Units) (minimum 1)
> > 
> > 
> > Remember, you need two Warlocks in the uint in order for it to be a valid target for this Stratagem 😉
> 
> It only works for Standart Warlocks, not for a Group of Warlock-Skyrunners, that have to been added as well because the Keywords are the same.

Yup, this is fixed on Master and will be in the next release :-)

**Comment by FarseerVeraenthis** [comment]
I plan to re-release tonight. For planned future developments, refer to #11035 
After this release, please report any further bugs in the usual way.
Thanks for everyone's help and suggestions so far!!

**Comment by TheGrayKing** [comment]
Not sure if this was already mentioned but the Craftworld Altansar Warlord Traits don't appear when you select it as your Craftworld

**Comment by FarseerVeraenthis** [comment]
> Not sure if this was already mentioned but the Craftworld Altansar Warlord Traits don't appear when you select it as your Craftworld

Thanks, this has been mentioned previously and will be included in the next release :+1:

**Comment by Valorcalls** [comment]
> Thank you for all the amazing work!
> 
> Dukhari should have access to Corsair datasheets but do not currently. The Way Seeker is also missing its Witch staff
> 
> Thanks!

Do keep the weakling kin rule in mind when discussing corsairs and drukari.

**Comment by marradius** [comment]
Don't know if u released yet, but I have downloaded the file from here to try it and noticed 2 bugs. Shrine relics cost 1CP each, but thats isn't how it works: you can add 2 of them as your free relic. Also even if you choose the stratagem Relics of the Shrines, the relics reduce the CP by 1 each when you should be able to get 2 relics usign that 1CP stratagem.

**Comment by FarseerVeraenthis** [comment]
> Don't know if u released yet, but I have downloaded the file from here to try it and noticed 2 bugs. Shrine relics cost 1CP each, but thats isn't how it works: you can add 2 of them as your free relic. Also even if you choose the stratagem Relics of the Shrines, the relics reduce the CP by 1 each when you should be able to get 2 relics usign that 1CP stratagem.

Good Catch - snuck in there just in time :+1:

**Comment by Boz83** [comment]
Hi, just like to say great job you have done. I know there is a comment about the Shrine relics and the CP allocation but the warp spider one "Spiders Bite" doesn't appear on the exarch
