### ISSUE TITLE
Aeldari CAT's: Feature Developments

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#11035]
- [x] Ynnari Detachments - mixed unit validation. Currently there is no validation of the requirement for a ratio of at least 1:1 Asuryani unit per other unit in each Battlefield Role slot.
 - [x] Increase costs of Drukhari units. This is not currently implemented, but it needs to be!!

- [x] Corsair Unit Availability - Enable access directly from other Aeldari CAT's (requires units and all linked wargear and weapons to be moved to the Ynnari CAT). Currently Corsair units can be selected by adding a child detachment of Asuryani into either Harlequins or Drukhari.

- [x] Legends Unit Availability - These units have 'old' rules references to the previous Codex: Craftworlds, but it could be argued they are valid for non-matched play games. They need to be re-instated, along with all their profiles, rules and selections - which is not the work of a minute...!!

**Comment by darkpsycer** [comment]
When I select to give a Harlequin a Treasure of the Aeldari this error pops up
![Screenshot 2022-03-10 230836](https://user-images.githubusercontent.com/101369273/157770378-10a710d9-6ba6-4556-92ca-dcc604b00fee.png)
.

**Comment by Kayzenchaos** [comment]
The Troupe leader should have access to the Embrace and Caress.  The way the data sheet is worded is up to two models.  From my understanding that would mean any two models in the unit for the special weapons which would include the leader.

**Comment by FarseerVeraenthis** [comment]
> The Troupe leader should have access to the Embrace and Caress. The way the data sheet is worded is up to two models. From my understanding that would mean any two models in the unit for the special weapons which would include the leader.

I thought I fixed this already... I'll try again 😸

**Comment by crispyjello** [comment]
Hey @FarseerVeraenthis I think you are doing a great job. 

I can't see any Harlequin units far a Ynnari detachment after selecting the Ynnari craftworld attribute. Wondering if I've selected it wrong.

Keep up the good work.

**Comment by FarseerVeraenthis** [comment]
> Hey @FarseerVeraenthis I think you are doing a great job.
> 
> I can't see any Harlequin units far a Ynnari detachment after selecting the Ynnari craftworld attribute. Wondering if I've selected it wrong.
> 
> Keep up the good work.

Currently you need to add a Harlequins detachment as a child detachment to the Craftworld parent detachment. This will change and all valid units will be available directly from the Craftworld Army List with the next release of data.
(And thanks 😺 )

**Comment by FarseerVeraenthis** [comment]
work on re-introducing Legends units has begun :-)
You will now be able to add Legends units by adding a sub-detachment to the main detachment.

**Comment by dalamar666** [comment]
Do we still need to select a sub Craftworld detachment to get Corsairs in an Ynnari Detachment? they do not show up.

**Comment by FarseerVeraenthis** [comment]
> Do we still need to select a sub Craftworld detachment to get Corsairs in an Ynnari Detachment? they do not show up.

You cannot run Corsairs in a Ynnari detachment...

**Comment by dalamar666** [comment]
> > Do we still need to select a sub Craftworld detachment to get Corsairs in an Ynnari Detachment? they do not show up.
> 
> You cannot run Corsairs in a Ynnari detachment...

My God I'm dumb how the $%&^ did I miss that. Thank you.

**Comment by FarseerVeraenthis** [comment]
had a brainwave about the Ynnari validation, should be in the next release, it has had minimal testing, feedback would be appreciated.
