### ISSUE TITLE
Nephilim validation

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#11397]
- [x] Aeldari
     - [x] Craftworlds
     - [x] Drukhari
     - [x] Harlequins 
     - [x] Ynnari
- [x] Chaos
     - [x] Chaos Knights
     - [x] Chaos Space Marines (as part of new Codex work)
     - [x] Daemons - not doing until new Codex
     - [x] Death Guard
     - [x] Thousand Sons
     - [x] FW Heretic Astartes
     - [x] FW Renegade and Heretics
     - [x] Gellerpox Infected
     - [x] Servants of the Abyss
     - [x] Titanicus Traitoris
- [x] Imperium
     - [x] Adepta Sororitas
     - [x] Adeptus Astra Telepathica
     - [x] Adeptus Custodes
     - [x] Adeptus Mechanicus
     - [x] Astra Cartographcia
     - [x] Astra Militarum
     - [x] Black Templars
     - [x] Blackstone Fortress
     - [x] Blood Angels
     - [x] Dark Angels
     - [x] Deathwatch
     - [x] Euclidian Starstriders
     - [x] FW Adeptus Astartes
     - [x] FW DKoK
     - [x] FW Elysians
     - [x] Grey Knights
     - [x] Imperial Fists
     - [x] Imperial Knights
     - [x] Inquisition
     - [x] Iron Hands
     - [x] LotD
     - [x] Officio Assassinorum
     - [x] Raven Guard
     - [x] Salamanders
     - [x] Space Marines
     - [x] Space Wolves
     - [x] Titan Legions
     - [x] Ultramarines
     - [x] White Scars
- [x] Xenos 
     - [x] Necrons
     - [x] Orks
     - [x] T'au Empire
     - [x] Tyranids
     - [x] Genestealer Cults

**Comment by wizard311** [comment]
@DrTobogganMD would really appreciate Necrons being Nephilim Validated.  I am really struggling with the CP issues involved with Warlord Traits and Named Characters being forced to take warlord traits (should be able to choose whether to take them not forced to)  Also the Silent King produces 3 cp as well as cancels the cp cost of 1 detachment.
