### ISSUE TITLE
Nephilim Dataslate

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#11418]
- [x] Astra Militarum
  - Vehicles gain Armour of Contempt
> ‘Hammer of the Emperor: If every unit from your army has the Astra Militarum keyword (excluding Agent
of the Imperium and Unaligned units), and if every <Regiment> unit in your army is drawn from the same regiment, then each time an Astra Militarum model from your army makes a ranged attack, an unmodified hit roll of 6 automatically wounds the target.’ 
Designer’s Note: Militarum Tempestus units will benefit from this rule if they are included in an army alongside other Astra Militarum units (e.g. Cadians units, Catachans units etc.) but if they are from a Tempestus Scions regiment (see Psychic Awakening: The Greater Good), they must all be from the same Tempestus Scions regiment in order to gain this rule.
  - [x] ASTRA MILITARUM TITANIC get a +2 save
- [x] Adepta Sororitas
  - No changes
- [x] Adeptus Custodes
  - No changes
- [x] Adeptus Mechanicus
  - No changes
- [x] Drukhari
  - No changes
- [x] Asuryani
  - Add the following:
  - [x] Add the following to the Hail of Doom Far-flung Craftworld Attribute: ‘You cannot select this Far-flung Craftworld Attribute if you have selected any other Far-flung Craftworld Attributes, and if you select this Far-flung Craftworld Attribute you cannot select a second.

- [x] Space Marines
    -  Honour Guard; Honour Guard of Macragge should use new bodyguard ability.
- [x] CSM
  - Remove the following:
  - [x] _DttFE is not in the new Codex_ ~~Change the Death to the False Emperor ability to read: ‘Each time a model with this ability makes a melee attack, a hit roll of 6+ scores one additional hit.’~~
  - Add the following: 
  - [x] Change the second bullet point of the Iron Within, Iron Without (Iron Warriors) Legion trait to read: ‘Each time an attack is made against a unit with this trait, that attack’s wound roll cannot be re-rolled.
- [x] Death Guard
  - No changes
- [x] Tyranids
  - Add the following:
  - [x] Add the following to the Rare Organisms Detachment ability: ‘If your army contains one or more Hive Tyrant models, one of them must be selected as your Warlord.’
  - [x] Replace the first paragraph of the Synaptic Imperative ability with: ‘If every unit from your army has the Hive Tendril keyword (excluding Unaligned units) and each of those units (excluding Living Artillery units) is from the same hive fleet, then while your Warlord is on the battlefield, Synapse units from your army have a Synaptic Imperative ability depending on which one is currently active for your army.
  - [x] When playing a matched play game, players cannot swap out the Adaptive element of their Hive Fleet Adaptation at the start of the battle after determining who has the first turn – if they wish to do so, this must instead be done during the Muster Armies step, and the player’s selection written on their army roster.
- [x] T'au Empire
  - No changes
- [x] Necrons
  - Add the following:
  - [x] Add CORE to Triarch Praetorians; all Necrons Vehicle datasheets.
  - [x] Command Protocols ability as follows:
> Change the Command Protocols ability as follows:
■ Replace the Noble keyword in all instances with Necrons Character.
■ Replace the last sentence of the penultimate paragraph with: ‘Until the assigned command protocol stops being active, while a unit that is eligible to benefit from this ability is on the battlefield, that unit benefits from the selected directive.’
■ Replace the last paragraph with: ‘In addition, if all units from your army are from the same dynasty (excluding Dynastic Agent, C’tan Shard and Unaligned units), select one command protocol that has not been assigned to a battle round (there will typically only be one). That command protocol is active in every battle round in addition to the one assigned to that battle round – select which directive your units will benefit from at the start of each battle round. Note that if this additional command protocol is the one described in your dynasty’s code, this means both of its directives apply to all units with this ability in your army in every battle
round, in addition to the protocol assigned to that battle round. The available command protocols are shown below.’
■ Designer’s Note: Some rules refer to ‘the active command protocol’, in these instances these rules refer to all command protocols that are active for your army
- [x] Harlequins
  - Add the following:
  - [x] Ignore the table listed in the Luck of the Laughing God ability. Instead, at the start of the battle round, you gain 0 Luck re-rolls, regardless of the battle size. You can only gain Luck re-rolls by making a Luck of the Laughing God roll.
  - [x] Change the Mirror Architect Pivotal Role to read: ‘In your Command phase, select one friendly <Saedath> Core unit within 9" of this model. Until the start of your next Command phase, each time an enemy unit is selected to shoot, when measuring the range to any model in that <Saedath> unit, it is considered to be an additional 6" away from the shooting model.
  - [x] Change the Favour of Cegorach Warlord Trait to read: ‘Once per turn, when you make a melee hit roll, a melee wound roll or a saving throw for this Warlord, after making the roll, you can treat the result as an unmodified roll of 6 instead.’
  - [x] Change the first bullet point of the Light Saedath Characterisation to read: ‘Each time an attack is made against a unit with this characterisation, if the attacking model is more than 18" away, an unmodified hit roll of 1-3 for that attack fails, irrespective of any abilities that the weapon or the model making that attack may have.’
  - [x] Change the first bullet point of the Dark Saedath Characterisation to read: ‘Each time a model with this characterisation is destroyed by a melee attack, roll one D6: on a 4+, after the attacking model’s unit has finished making its attacks, it suffers 1 mortal wound (a unit can suffer a maximum of 6 mortal wounds per phase as a result of this ability).
- [x] Orks
  - [x] Ork buggies are now 3 of each model
  - Replace the following:
> STAGE 1: CALL DA WAAAGH!
■ Orks Core and Orks Character units from your
army are eligible to declare a charge even if they
Advanced this turn.
■ Add 1 to the Strength and Attacks characteristics of
Orks models from your army.
■ Orks models from your army have a 5+
invulnerable save.
STAGE 2: GET STUCK IN!
■ Add 1 to the Strength and Attacks characteristics of
Orks models from your army.
■ Orks models from your army have a 6+
invulnerable save.

**Comment by Shure610** [comment]
Hi, 
In the DG chart, says there is no change, but in the MUNITORUM FIELD MANUAL 2022 MK II, there is some changes in the points for several units. Thanks for keep the data updated. Regards!

![2022-06-23 12_34_56-mYZ4b5gZUiktj4GI pdf](https://user-images.githubusercontent.com/108085434/175349976-2c6230d9-1c15-4db8-a899-a15af49869d0.jpg)

**Comment by Technoblazed** [comment]
This tracker has nothing to do with the points values.
