### ISSUE TITLE
Nephilim Points Tracker

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#11415]
- [x] Space Marines
  - [x] Ultramarines
  - [x] White Scars 
  - [x] Salamanders
  - [x] Imperial Fists
  - [x] Black Templars 
  - [x] Raven Guard 
  - [x] Iron Hands
  - [x] Blood Angels 
  - [x] Dark Angels 
  - [x] Space Wolves 
  - [x] Deathwatch
- [x] Grey Knights
- [x] Adepta Sororitas
- [x] Adeptus Custodes
- [x] Officio Assassinorum
- [x] Astra Militarum
- [x] Adeptus Mechanicus
- [x] Imperial Knights
- [x] Inquisition
- [x] Chaos Space Marines (Points are for new Codex)
- [x] Death Guard
- [x] World Eaters
- [x] Thousand Sons
- [x] Chaos Daemons 
- [x] Chaos Knights
- [x] Asuryani and Anhrathe
- [x] Harlequins
- [x] Drukhari
- [x] Necrons
- [x] Orks
- [x] T’au Empire
- [x] Tyranids
- [x] Genestealer Cults 
- [x] Unaligned Fortifications
- [x] Forge World Points Values
  - [x] Space Marines 
  - [x] Grey Knights
  - [x] Astra Militarum
  - [x] Inquisition
  - [x] Adeptus Custodes 
  - [x] Adeptus Mechanicus
  - [x] Imperial Knights 
  - [x] Titan Legions
  - [x] Chaos Space Marines
  - [x] Death Guard
  - [x] Chaos Daemons 
  - [x] Chaos Knights
  - [x] Chaos Titan Legions
  - [x] Craftworlds 
  - [x] Drukhari
  - [x] Necrons
  - [x] Orks 
  - [x] T’au Empire 
  - [x] Tyranids
  - [x] Miscellaneous
