### ISSUE TITLE
Imperium - Astra Militarum: 9th Edition Checklist

### ISSUE THREAD

**Issue by AbonShell** [BSData/wh40k-9e#12011]
- [x] Detachment Abilities
- [x] Regimental Doctrines
- [x] List Building Stratagems
     - [x] add the logic for use with command squads specifics. 
- [x] Tank Aces - restrict one of each per roster
     - [x] Vaunted Praetorian
     - [x] Meticulous Calibrator
     - [x] Mechanical Pack Rat
     - [x] Veteran Commandeer
          - [x] add logic for above
     - [x] Knight of Piety
     - [x] Master of Camouflage
     - [x] Steel Commissar
- [x] Psykana Discipline
- [x] Warlord Traits
- [x] Relics
- [x] Turret Weapons
- [x] Regimental tactics
- [x] Voice of command
     - [x] try and make work the single SE or just go with unique profiles
- [x] Regimental Orders
- [x] Models
     - [x] HQs
          - [x] Lord Solar Leontus
          - [x] Ursula Creed
          - [x] Cadian Castellan
          - [x] Tank Commander
          - [x] Platoon Command Squad
          - [x] Cadian Command Squad
          - [x] Gaunt's Ghosts
          - [x] Militarum Tempestus Command Squad
     - [x] Regimental Ataches and Bodyguards
          - [x] Master of Ordnance
          - [x] Officer of the Fleet
          - [x] Astropath
          - [x] Ogryn Body Guard
          - [x] Nork Deddog
     - [x] Troops
          - [x] Infantry Squad
          - [x] Cadian Shock Troops
          - [x] Death Korps of Krieg
          - [x] Catachan Jungle Fighters
     - [x] Elites
          - [x] Sly Marbo
          - [x] Karskin
          - [x] Regimental Preacher
          - [x] Sergeant Harker
          - [x] Regimental Enginseer
          - [x] Munitorum Servitors
          - [x] Commissar
          - [x] Ogryns
          - [x] Bullgryns
          - [x] Ratlings
          - [x] Tempestus Scions
     - [x] Fast Attack
          - [x] Attilan Rough Riders
          - [x] Scout Sentinels
          - [x] Armoured Sentinels
          - [x] Hellhound
     - [x] Heavy Support
          - [x] Rogal Dorn Battle Tank
          - [x] Heavy Weapons Squad
          - [x] Field Ordnance Battery
          - [x] Leman Russ Battle Tanks
          - [x] Basilisk
          - [x] Hydra
          - [x] Manticore
          - [x] Wyvern
          - [x] Deathstrike
     - [x] Flyer
          - [x] Valkyrie
     - [x] Dedicated Transport
          - [x] Chimera
          - [x] Taurox
          - [x] Taurox Prime
     - [x] Fortification
          - [x] Aegis Defense Line
     - [x] Lord of War
          - [x] Baneblade
          - [x] Banehammer
          - [x] Banesword
          - [x] Doomhammer
          - [x] Hellhammer
          - [x] Shadowsword
          - [x] Stormlord
          - [x] Stormsword

**Comment by ColonialAF** [comment]
Playing around with this file, a couple of quick things I noticed:

* There is no way to give a tank commander a relic
* The only way to give a tank commander a wlt is if they are the warlord (no stratagem for it)
* Giving a command squad Superior Tactical Training doesn't have a way to pick which other type of orders they know (not as important)

**Comment by ColonialAF** [comment]
Ah, fiddling around some more, it looks like you just can't give a warlord of any kind a relic in Eternal War. Of the tank commander isn't the warlord, I can use the strategem, but then the actual warlord (a platoon commander in this case) couldn't take one.

**Comment by ShadeBladee** [comment]
When is this going live? Would love to get my hands on your sweet sweet battlescribe data!

**Comment by AbonShell** [comment]
@ShadeBladee when the standalone codex is out

**Comment by Kal451** [comment]
not sure if should be opening issues for a in progress branch of just comment here, but noticed a spelling error with the Superior Tactical Training Trait. Refers to "this warlord Train" instead of "trait".

if i see anything else should it be comment or report issue? or wait till full release for a tidy pass?

**Comment by AbonShell** [comment]
@Kal451 I mean, you can just report it here. Since it's technically not live yet. I've gotten most of the stuff. Just a matter of tiny things

**Comment by ShadeBladee** [comment]
> @ShadeBladee when the standalone codex is out

I'd love to check it out before then, is there any way I could get a hold how the files early?

**Comment by AbonShell** [comment]
@ShadeBladee downloading the branch as a zip and replacing your current data with the downloaded branch.

**Comment by nyhmn** [comment]
sorry to bother, but it seems like when i try to download the .cat files it just shows as text. I get no option to download as a Zip. When i do download the files show as security catalog file. any guidance here would be much appreciated!

**Comment by CrumpetNinja** [comment]
Just a few nitpicky things/typos I've noticed:

1 - The "Cadian Shock Troops" squad are missing their "shock troops", and "regimental tactics" special rules from their unit entry.

2 - The medipack rules text for the "platoon command squad", "Cadian command squad", and "Tempestus command squad" all contain the same typo.
(They say "D^" instead of "D6")

3 - "Tempestor Prime" is listed as "Tempestor Priime"

4 - scout sentinels are missing "Regimental Tactics" in their unit entry

**Comment by VAYASEN** [comment]
H

> @ShadeBladee downloading the branch as a zip and replacing your current data with the downloaded branch.

Hi there.  Great work on the AM.  How exactly do I do that?  I have the Codex but would really love to have is on BS.  Where do I download the branch as a zip etc.

Thanks again for your effort.

**Comment by MrMayhem246** [comment]
Good evening,  I have BS on android mobile and would love to download the file for the update. I've been trying to figure it for the past few days and haven't managed it, is there a way to actually do that?

**Comment by AbonShell** [comment]
@VAYASEN @MrMayhem246 @nyhmn we aren't providing support for those that are trying to install the beta branch. It's complicated and if not done right will just cause more headaches.

**Comment by VAYASEN** [comment]
> @VAYASEN @MrMayhem246 @nyhmn we aren't providing support for those that are trying to install the beta branch. It's complicated and if not done right will just cause more headaches.

Understood.  Wasnt asking for support as such, just wondered why you got the file you mentioned above 'downloading the branch as a zip and replacing your current data with the downloaded branch'.     

Not looking to hassle you at all by the way, greatly appreciate the work you are doing.

**Comment by toughcare** [comment]
When I select a Veteran Commandeer doctrine and the same doctrine for my Kasrkin - I get a an error that I have 1 too many selections of the doctrine(Elite sharpshooters for example).

**Comment by toughcare** [comment]
When selecting a relic for my command squad I cannot select the "Order of the bastium stellaris"

**Comment by AbonShell** [comment]
> When selecting a relic for my command squad I cannot select the "Order of the bastium stellaris"

It was missing in the relic list. Fixed.

> When I select a Veteran Commandeer doctrine and the same doctrine for my Kasrkin - I get a an error that I have 1 too many selections of the doctrine(Elite sharpshooters for example).

Working as intended. Both state that "select one doctrine from the Regimental Doctrines section that no other unit from your army has"

**Comment by toughcare** [comment]
> Working as intended. Both state that "select one doctrine from the Regimental Doctrines section that no other unit from your army has"

Sorry missed that one! :)

**Comment by Randalf98** [comment]
@AbonShell is there a plan to include the contents of the imperial armoury compendium adding the astra militarum forgeworld options? Or will you abe awaiting an IAC FAQ to come with the full release of the new codex?

**Comment by AbonShell** [comment]
@Randalf98 currently none of them really *work* with the new codex, so they've been hidden.

**Comment by Uncle-Mel** [comment]
> @Randalf98 currently none of them really _work_ with the new codex, so they've been hidden.

Legends units are still in there though, would love to see a unit filter like the T'au cat has.

Also, Hydra cannon still has te old ability mentioned.

**Comment by jordiMartinB** [comment]
The PL value of the attilan Rough riders is stuck to 10PL if you take more than 1 unit. Points values are OK.

**Comment by betttris13** [comment]
Looks like baneblade variants point costs are off. The first set of sponsions is now part of the base cost not a separate cost so all the point costs are up 40 points.

**Comment by AbonShell** [comment]
> Looks like baneblade variants point costs are off. The first set of sponsions is now part of the base cost not a separate cost so all the point costs are up 40 points.

Incorrect, you pay all costs listed. Lascannons have a cost, so you pay it. It does not matter if they are default or not. If that was the case, it would say "lascanon (additional)"  as it does for the rogal dorn's heavy stubber

**Comment by betttris13** [comment]
It was made clear in the rules preview that the first set of sponsions is part of the cost: "The Baneblade has also seen some improvements. Your first two sponsons packing lascannons and twin heavy bolters are rolled into its base cost, making it significantly cheaper than before. And don’t worry – you can still add an extra two sponsons if 12 barrels of death weren’t enough. Those are now cheaper too!" (https://www.warhammer-community.com/2022/11/02/rogal-dorn-size-comparison-how-the-new-tank-matches-up-in-scale-and-rules/). I think this needs clarifying in an FAQ as the RAW in the codex doesn't specify clearly although it does specify the second sponsons are additional.

On another note there is a typo in the bullgryn slab shield: "savea".

**Comment by AbonShell** [comment]
Warhammer community isn't a source of rules. They've been very wrong on things about stuff when books have come out. As it stands, the data on the sponsons are correct. No where in the book does it say the first pair of lascannons are free.

**Comment by betttris13** [comment]
Fair enough, guess we will just have to wait and see,

**Comment by VAYASEN** [comment]
So is there no way to try the AM list on BS as it is (at our own risk?).   I have so little time for the paperwork side of 40k, I coudlnt even begin to make my list from just the Cadia Stands Codex (which I have)....I just dont have time....so BS is a life saver for me to throw a list together, see points and plan accordingly.     PS thanks for all the great work.

**Comment by CrumpetNinja** [comment]
The weapon option logic on the "Cadian Command squad" is slightly incorrect.

Only 1 guardsmen (excluding the officer) can replace their laspistol with a plasma pistol or bolt pistol. 
Currently Battlescribe will allow you to replace the pistol of the Vox operator, and the "Laspistol+chainsword" guardsmen at the same time without throwing a validation error.

**Comment by AbonShell** [comment]
@VAYASEN 
<https://github.com/BSData/wh40k/archive/refs/heads/Guard9E-Update.zip>

Android
Navigate to Android>data>net.battlescribe.mobile.rostereditor>files>data>Warhammer 40,000 9th edition

Windows
C:\Users\ "username"\BattleScribe\data\Warhammer 40,000 9th Edition

Delete all files in those folders, extract the zip in there.

If you are on iOS, you have to set up dropbox.



> The weapon option logic on the "Cadian Command squad" is slightly incorrect.
> 
> Only 1 guardsmen (excluding the officer) can replace their laspistol with a plasma pistol or bolt pistol. Currently Battlescribe will allow you to replace the pistol of the Vox operator, and the "Laspistol+chainsword" guardsmen at the same time without throwing a validation error.

Fixed in the latest push I just did.

**Comment by VAYASEN** [comment]
> @VAYASEN https://github.com/BSData/wh40k/archive/refs/heads/Guard9E-Update.zip
> 
> Android Navigate to Android>data>net.battlescribe.mobile.rostereditor>files>data>Warhammer 40,000 9th edition
> 
> Windows C:\Users\ "username"\BattleScribe\data\Warhammer 40,000 9th Edition
> 
> Delete all files in those folders, extract the zip in there.
> 
> If you are on iOS, you have to set up dropbox.
> 
> > The weapon option logic on the "Cadian Command squad" is slightly incorrect.
> > Only 1 guardsmen (excluding the officer) can replace their laspistol with a plasma pistol or bolt pistol. Currently Battlescribe will allow you to replace the pistol of the Vox operator, and the "Laspistol+chainsword" guardsmen at the same time without throwing a validation error.
> 
> Fixed in the latest push I just did.

Thank you for that, much appreciated.

**Comment by helios3019** [comment]
Thank you for your work on this, you've done a brilliant job. Just to nitpick slightly, part of the "Born Soldiers" doctrine is missing:
The auto-wounds you get from sixes to hit are all counted as natural sixes to wound.

**Comment by LcATD** [comment]
Heya! been looking around far and wide on the internet but the search came fruitless, so I figured it'd probably be best to put this here: I've been struggling to get a few things onto a roster: a Cadian regiment, and FW armageddon pattern vehicles (armageddon pattern basilisk for instance).
Namely, no matter how hard I try, Knight Cmdr. Pask does not want to show up. I've noticed someone asking similar things on issue #6743, but I've no idea how or where to find the config for this 'No Force Org Slot' thing. And for the vehicles, they don't show up separately on the model list, and neither can I find upgrade options from their regular variants...
any idea if this is a bug or if I'm just being dumb? Using the PC client btw. Cheers.

**Comment by AbonShell** [comment]
> Heya! been looking around far and wide on the internet but the search came fruitless, so I figured it'd probably be best to put this here: I've been struggling to get a few things onto a roster: a Cadian regiment, and FW armageddon pattern vehicles (armageddon pattern basilisk for instance). Namely, no matter how hard I try, Knight Cmdr. Pask does not want to show up. I've noticed someone asking similar things on issue #6743, but I've no idea how or where to find the config for this 'No Force Org Slot' thing. And for the vehicles, they don't show up separately on the model list, and neither can I find upgrade options from their regular variants... any idea if this is a bug or if I'm just being dumb? Using the PC client btw. Cheers.

Pask no longer exists.

**Comment by LcATD** [comment]
> > Heya! been looking around far and wide on the internet but the search came fruitless, so I figured it'd probably be best to put this here: I've been struggling to get a few things onto a roster: a Cadian regiment, and FW armageddon pattern vehicles (armageddon pattern basilisk for instance). Namely, no matter how hard I try, Knight Cmdr. Pask does not want to show up. I've noticed someone asking similar things on issue #6743, but I've no idea how or where to find the config for this 'No Force Org Slot' thing. And for the vehicles, they don't show up separately on the model list, and neither can I find upgrade options from their regular variants... any idea if this is a bug or if I'm just being dumb? Using the PC client btw. Cheers.
> 
> Pask no longer exists.

Huh...I suspected that to be a possible case but couldn't find that info anywhere. Thanks for letting me know!
