### ISSUE TITLE
Implementation of Partial Crusade Support

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k-9e#12030]
Partial Crusade Support checklist

- [ ] GST
- [ ] Aeldari
     - [ ] Craftworlds
     - [ ] Drukhari
     - [ ] Harlequins 
     - [ ] Ynnari
- [ ] Chaos
     - [x] Chaos Knights
     - [x] Chaos Space Marines
     - [x] Daemons
     - [ ] Death Guard
     - [x] Thousand Sons
     - [x] FW Heretic Astartes
     - [ ] FW Renegade and Heretics
     - [ ] Gellerpox Infected
     - [ ] Servants of the Abyss
     - [ ] Titanicus Traitoris
- [ ] Imperium
     - [ ] Adepta Sororitas
     - [ ] Adeptus Astra Telepathica
     - [x] Adeptus Custodes
     - [ ] Adeptus Mechanicus
     - [ ] Astra Cartographcia
     - [x] Astra Militarum
     - [ ] Black Templars
     - [ ] Blood Angels
     - [ ] Dark Angels
     - [ ] Deathwatch
     - [ ] Euclidian Starstriders
     - [ ] FW Adeptus Astartes
     - [ ] FW DKoK
     - [ ] Grey Knights
     - [ ] Imperial Fists
     - [ ] Imperial Knights
     - [ ] Inquisition
     - [ ] Iron Hands
     - [ ] LotD
     - [ ] Officio Assassinorum
     - [ ] Raven Guard
     - [ ] Salamanders
     - [ ] Space Marines
     - [ ] Space Wolves
     - [ ] Titan Legions
     - [ ] Ultramarines
     - [ ] White Scars
- [ ] Xenos 
     - [ ] Leagues of Votann
     - [x] Necrons
     - [ ] Orks
     - [ ] T'au Empire
     - [ ] Tyranids
     - [ ] Genestealer Cults

Currently supporting only tracking battle honours (including crusade relics)

**Comment by Mad-Spy** [comment]
@WindstormSCR, can you maybe update this with what actually needs to be done in the cats?

**Comment by WindstormSCR** [comment]
Procedure:

1. Create Local "Battle Honours" SSEG with the GST battle honours SSEG as a sub-section
2. Limit new SSEG to only display if crusade gametype
3. add new codex specific battle honours SSEGs under a "Battle Honours (Codex)" SSEG
4. Constrain as appropriate, for complicated edge cases or difficult implementation leave validation to the user (example: chaos boons on squad champions)
5. Ensure Crusade relics are 1/roster, but otherwise do not interact with standard relic system.

**Comment by felixlinker** [comment]
I could try adding Adepta Sororitas crusade rules. Novice to data editing, so cannot promise anything. Is someone already on this?

**Comment by maciej-kolodziejczak** [comment]
Hi there, I'm taking the DG crusade rules implementation, if anyone works on that already please HMU.

**Comment by Mad-Spy** [comment]
No further work is going to be done on this.
