### ISSUE TITLE
Chaos FAQ Implementation Tracker

### ISSUE THREAD

**Issue by cartag** [BSData/wh40k-9e#609]
Tracking my progress.

- [x] Chaos Predator damage table
- [x] Daemon Prince PL if winged
- [x] Ahriman PL
- [x] Exalted Sorc, PL
- [x] DG Sorc
- [x] Kairos EF
- [x] Daemon DP wounds
- [x] Exalt Sorc points
- [x] Chaos Bastion somehow forgotten entirely, needs implemented
