### ISSUE TITLE
Warhammer 40,000 9th Edition Checklist

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-9e#7349]
Just a tracker for the 9th Edition prepwork. Check the box if you do something!

- [x] Aeldari - Craftworlds.cat: 9e FAQ
- [x] Aeldari - Craftworlds.cat:   MFM2020 Points
- [x] Aeldari - Drukhari.cat: 9e FAQ
- [x] Aeldari - Drukhari.cat:   MFM2020 Points
- [x] Aeldari - FW Corsairs.cat: 9e FAQ
- [x] Aeldari - FW Corsairs.cat:   MFM2020 Points
- [x] Aeldari - Harlequins.cat: 9e FAQ
- [x] Aeldari - Harlequins.cat:   MFM2020 Points
- [x] Aeldari - Ynnari.cat: 9e FAQ
- [x] Aeldari - Ynnari.cat: MFM2020 Points
- [x] Chaos - Chaos Space Marines.cat: MFM2020 Points
- [x] Chaos - Chaos Space Marines.cat: 9e FAQ
- [x] Chaos - Daemons.cat: 9e FAQ
- [x] Chaos - Daemons.cat: MFM2020 Points
- [x] ~~Chaos - Dark Mechanicum.cat:   MFM2020 Points~~
- [x] ~~Chaos - Dark Mechanicum.cat: 9e FAQ~~
- [x] Chaos - Death Guard.cat: 9e FAQ
- [x] Chaos - Death Guard.cat:   MFM2020 Points
- [x] Chaos - FW Heretic Astartes.cat:   MFM2020 Points
- [x] Chaos - FW Heretic Astartes.cat:   9e   FAQ
- [x] ~~Chaos - FW Renegades and Heretics.cat: 9e FAQ~~
- [x] ~~Chaos - FW Renegades and Heretics.cat: MFM2020 Points~~
- [x] Chaos - Gellerpox   Infected.cat: MFM2020 Points
- [x] Chaos - Gellerpox Infected.cat: 9e FAQ
- [x] Chaos - Questor Traitoris.cat: Detachment Support
- [x] Chaos - Questor Traitoris.cat: MFM2020 Points
- [x] Chaos - Questor Traitoris.cat: 9e FAQ
- [x] Chaos - Servants of the   Abyss.cat: 9e FAQ
- [x] Chaos - Servants of the   Abyss.cat: MFM2020 Points
- [x] Chaos - Thousand Sons.cat: 9e FAQ
- [x] Chaos - Thousand Sons.cat:   MFM2020 Points
- [x] Chaos - Titanicus Traitoris.cat: MFM2020 Points
- [x] Chaos - Titanicus Traitoris.cat: 9e FAQ
- [x] Fallen.cat: 9e FAQ
- [x] Fallen.cat: MFM2020 Points
- [x] Imperium - Adeptus Astra Telepathica.cat: 9e FAQ
- [x] Imperium - Adeptus Astra Telepathica.cat: MFM2020 Points
- [x] Imperium - Adeptus Custodes.cat: MFM2020 Points
- [x] Imperium - Adeptus Custodes.cat: 9e FAQ
- [x] Imperium - Adeptus Mechanicus.cat: 9e FAQ
- [x] Imperium - Adeptus Mechanicus.cat: MFM2020 Points
- [x] Imperium - Adeptus Ministorum.cat: 9e FAQ
- [x] Imperium - Adeptus Ministorum.cat: File Rename
- [x] Imperium - Adeptus Ministorum.cat: MFM2020 Points
- [x] Imperium - Astra Militarum - Library.cat: 9e FAQ
- [x] Imperium - Astra Militarum - Library.cat: MFM2020 Points
- [x] Imperium - Astra Militarum.cat: MFM2020 Points
- [x] Imperium - Astra Militarum.cat: 9e FAQ
- [x] Imperium - Black Templars.cat: MFM2020 Points
- [x] Imperium - Black Templars.cat: 9e FAQ
- [x] Imperium - Blackstone Fortress.cat: 9e FAQ
- [x] Imperium - Blackstone Fortress.cat: MFM2020 Points
- [x] Imperium - Blood Angels.cat: MFM2020 Points
- [x] Imperium - Blood Angels.cat: 9e FAQ
- [x] Imperium - Dark Angels.cat: 9e FAQ
- [x] Imperium - Dark Angels.cat: MFM2020 Points
- [x] Imperium - Deathwatch.cat: 9e FAQ
- [x] Imperium - Deathwatch.cat: MFM2020 Points
- [x] Imperium - Elucidian Starstriders.cat: 9e FAQ
- [x] Imperium - Elucidian Starstriders.cat: MFM2020 Points
- [x] Imperium - FW Adeptus Astartes.cat: 9e FAQ
- [x] Imperium - FW Adeptus Astartes.cat: MFM2020 Points
- [x] Imperium - FW Death Korps of Krieg.cat: 9e FAQ
- [x] Imperium - FW Death Korps of Krieg.cat: MFM2020 Points
- [x] Imperium - FW Elysians.cat: 9e FAQ
~~- [ ] Imperium - FW Elysians.cat: MFM2020 Points~~
- [x] Imperium - Grey Knights.cat: MFM2020 Points
- [x] Imperium - Grey Knights.cat: 9e FAQ
- [x] Imperium - Imperial Fists.cat: MFM2020 Points
- [x] Imperium - Imperial Fists.cat: 9e FAQ
- [x] Imperium - Inquisition.cat: 9e FAQ
- [x] Imperium - Inquisition.cat: MFM2020 Points
- [x] Imperium - Iron Hands.cat: 9e FAQ
- [x] Imperium - Iron Hands.cat: MFM2020 Points
- [x] Imperium - Legion of the Damned.cat: 9e FAQ
- [x] Imperium - Legion of the Damned.cat: MFM2020 Points
- [x] Imperium - Officio Assassinorum.cat: 9e FAQ
- [x] Imperium - Officio Assassinorum.cat: MFM2020 Points
- [x] Imperium - Questor Imperialis.cat: 9e FAQ
- [x] Imperium - Questor Imperialis.cat: Detachment Support
- [x] Imperium - Questor Imperialis.cat: MFM2020 Points
- [x] Imperium - Questor Imperialis.cat: File Rename
- [x] Imperium - Raven Guard.cat: 9e FAQ
- [x] Imperium - Raven Guard.cat: MFM2020 Points
- [x] Imperium - Salamanders.cat: 9e FAQ
- [x] Imperium - Salamanders.cat: MFM2020 Points
- [x] Imperium - Sisters of Silence.cat: 9e FAQ
- [x] Imperium - Sisters of Silence.cat: MFM2020 Points
- [x] Imperium - Space Marines - Library.cat: Indomitus Units
- [x] Imperium - Space Marines.cat: MFM2020 Points
- [x] Imperium - Space Marines.cat: 9e FAQ
- [x] Imperium - Space Wolves.cat: MFM2020 Points
- [x] Imperium - Space Wolves.cat: 9e FAQ
- [x] Imperium - Titan Legions.cat: 9e FAQ
- [x] Imperium - Titan Legions.cat: MFM2020 Points
- [x] Imperium - Titan Legions.cat: File Rename
- [x] Imperium - Ultramarines.cat:   MFM2020 Points
- [x] Imperium - Ultramarines.cat: 9e FAQ
- [x] Imperium - White_Scars.cat: 9e FAQ
- [x] Imperium - White_Scars.cat: File Rename
- [x] Imperium - White_Scars.cat: MFM2020 Points
- [x] Necrons.cat: 9e FAQ
- [x] Necrons.cat: MFM2020 Indomitus Units
- [x] Necrons.cat: MFM2020 Points
- [x] Orks.cat: 9e FAQ
- [x] Orks.cat: MFM2020 Points
- [x] T'au Empire.cat: 9e FAQ
- [x] T'au Empire.cat: MFM2020 Points
- [x] Tyranids - Genestealer Cults.cat: 9e FAQ
- [x] Tyranids - Genestealer Cults.cat: MFM2020 Points
- [x] Tyranids.cat: 9e FAQ
- [x] Tyranids.cat: MFM2020 Points
- [x] ~~Unaligned - Monsters and Gribblies.cat: 9e FAQ~~
- [x] Unaligned - Monsters and Gribblies.cat: MFM2020 Points
- [x] Warhammer 40,000.gst: 9e FAQ
- [x] Warhammer 40,000.gst: Detachment Support
- [x] Warhammer 40,000.gst: MFM2020 Points

Blast:

* [x] Chaos
* [x] Nidz
* [x] GSC
* [x] Orks
* [x] Necrons
* [x] T'au
* [x] Aeldari
* [x] Imperial Knights
* [x] Grey Knights
* [x] Adeptus Custodes
* [x] Adeptus Mechanicus
* [x] Astra Mili-what
* [x] Deathwatch
* [x] Space Viking Puppies
* [x] Dark Angels
* [x] Blood Angels
* [x] Imperium - Assassins
* [x] Imperium - Inquisition
* [x] Adeptus Sororitas
* [x] Blackstone Archeotech
* [x] Space Marines

**Comment by Mad-Spy** [comment]
GST point values are done for everything that was in Chaos. Mostly stuff shared with SM.

**Comment by CaptainGelb** [comment]
I have made a Branch with the Changes to Orks. The Forgeworld FAQ is not included:
Orks.cat: 9e FAQ 
Orks.cat: MFM2020 Points

**Comment by DessaiImrane** [comment]
I've submitted a PR for Partial Update for Space Wolves.

**Comment by DessaiImrane** [comment]
PR with completed updated points costs for SW. 
#7371

**Comment by DrTobogganMD** [comment]
Prep work done - Shipping today. Further work will be done via QA issues.
