### ISSUE TITLE
9th Edition MFM2020 Points QA Checklist

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#7363]
Tracker for points/PL costs QA review.
- [x] Aeldari - Craftworlds.cat
- [x] Aeldari - Drukhari.cat
- [x] Aeldari - FW Corsairs.cat
- [x] Aeldari - Harlequins.cat
- [x] Aeldari - Ynnari.cat
- [x] Chaos - Chaos Space Marines.cat
- [x] Chaos - Daemons.cat
- [x] Chaos - Death Guard.cat
- [x] Chaos - FW Heretic Astartes.cat
- [x] Chaos - Gellerpox Infected.cat
- [x] Chaos - Questor Traitoris.cat
- [x] Chaos - Servants of the Abyss.cat
- [x] Chaos - Thousand Sons.cat
- [x] Chaos - Titanicus Traitoris.cat
- [x] Fallen.cat
- [x] Imperium - Adeptus Astra Telepathica.cat
- [x] Imperium - Adeptus Custodes.cat
- [x] Imperium - Adeptus Mechanicus.cat
- [x] Imperium - Adeptus Sororitas.cat
- [x] Imperium - Astra Militarum.cat
- [x] Imperium - Black Templars.cat
- [x] Imperium - Blackstone Fortress.cat
- [x] Imperium - Blood Angels.cat
- [x] Imperium - Dark Angels.cat
- [ ] Imperium - Deathwatch.cat
- [x] Imperium - Elucidian Starstriders.cat
- [x] Imperium - FW Adeptus Astartes.cat
- [ ] Imperium - FW Death Korps of Krieg.cat
- [x] Imperium - Grey Knights.cat
- [x] Imperium - Imperial Fists.cat
- [x] Imperium - Inquisition.cat
- [x] Imperium - Iron Hands.cat
- [x] Imperium - Legion of the Damned.cat
- [x] Imperium - Officio Assassinorum.cat
- [x] Imperium - Imperial Knights.cat
- [x] Imperium - Raven Guard.cat
- [x] Imperium - Salamanders.cat
- [x] Imperium - Sisters of Silence.cat
- [x] Imperium - Space Marines.cat
- [x] Imperium - Space Wolves.cat
- [x] Imperium - Titan Legions.cat
- [x] Imperium - Ultramarines.cat
- [x] Imperium - White_Scars.cat
- [x] Necrons.cat
- [x] Orks.cat
- [x] T'au Empire.cat
- [x] Tyranids - Genestealer Cults.cat
- [x] Tyranids.cat
- [x] Unaligned - Monsters and Gribblies.cat

**Comment by DessaiImrane** [comment]
PR with completed updated points costs for SW. 
#7371

**Comment by williamcaw** [comment]
i think you can close this now  because of #7901 and #7899 is the current publications

**Comment by amis92** [comment]
Yeah I think so too. @Dunamis55 what do you think?

**Comment by Dunamis55** [comment]
Sure, I might do a quick pass over Deathwath and DKOK at some point too, but I'll close this down now.
