### ISSUE TITLE
40k PL Changes

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-9e#7899]
Tracker issue for 40k PL Changes.
https://www.warhammer-community.com/wp-content/uploads/2020/08/A643OEwxln6ZS8H4.pdf

- [x] Aeldari - Craftworlds.cat
- [x] Aeldari - Drukhari.cat
- [x] Aeldari - FW Corsairs.cat
- [x] Aeldari - Harlequins.cat
- [x] Aeldari - Ynnari.cat
- [x] Chaos - Chaos Knights.cat
- [x] Chaos - Chaos Space Marines.cat
- [x] Chaos - Daemons.cat
- [x] Chaos - Dark Mechanicum.cat - NO CHANGES
- [x] Chaos - Death Guard.cat
- [x] Chaos - FW Heretic Astartes.cat
- [x] Chaos - FW Renegade and Heretics.cat - STILL MISSING
- [x] Chaos - Gellerpox Infected.cat
- [x] Chaos - Servants of the Abyss.cat
- [x] Chaos - Thousand Sons.cat
- [x] Chaos - Titanicus Traitoris.cat
- [x] Fallen.cat
- [x] Imperium - Adepta Sororitas.cat
- [x] Imperium - Adeptus Astra Telepathica.cat
- [x] Imperium - Adeptus Custodes.cat
- [x] Imperium - Adeptus Mechanicus.cat
- [x] Imperium - Astra Militarum - Library.cat
- [x] Imperium - Astra Militarum.cat
- [x] Imperium - Black Templars.cat
- [x] Imperium - Blackstone Fortress.cat
- [x] Imperium - Blood Angels.cat
- [x] Imperium - Dark Angels.cat
- [x] Imperium - Deathwatch.cat
- [x] Imperium - Elucidian Starstriders.cat
- [x] Imperium - FW Adeptus Astartes.cat
- [x] Imperium - FW Death Korps of Krieg.cat
- [x] Imperium - FW Elysians.cat
- [x] Imperium - Grey Knights.cat
- [x] Imperium - Imperial Fists.cat
- [x] Imperium - Imperial Knights.cat
- [x] Imperium - Inquisition.cat
- [x] Imperium - Iron Hands.cat
- [x] Imperium - Legion of the Damned.cat
- [x] Imperium - Officio Assassinorum.cat - NO CHANGES
- [x] Imperium - Raven Guard.cat
- [x] Imperium - Salamanders.cat
- [x] Imperium - Sisters of Silence.cat
- [x] Imperium - Space Marines.cat
- [x] Imperium - Space Wolves.cat
- [x] Imperium - Titan Legions.cat
- [x] Imperium - Ultramarines.cat
- [x] Imperium - White Scars.cat
- [x] Necrons.cat
- [x] Orks.cat
- [x] T'au Empire.cat
- [x] Tyranids - Genestealer Cults.cat
- [x] Tyranids.cat
- [x] Unaligned - Monsters and Gribblies.cat

**Comment by tag8833** [comment]
PR #7907 takes care of orks.

**Comment by DrTobogganMD** [comment]
Done!!
