### ISSUE TITLE
Combined Aeldari Issue Tracker

### ISSUE THREAD

**Issue by DrTobogganMD** [BSData/wh40k-9e#8056]
Since the Aeldari cats are undergoing a rewrite - I'm combining the various issues here for the author to track.

**Dark Eldar:**

- [x] - There's some shared boxes in the archon for legends tags that aren't unshared too. Jon - Discord (Stupid effing Legends can just do one...!)
- [ ] - Kabalite Warriors add 5 Points to total, if you copy a Unit with 8 Warriors 1 Sybalit 1 Warrior with Heavy weapon. #8047 
-  - Note this happens due to a BS bug, but it might be able to be worked around? It has to do with cost incremental modifiers.

**Craftworlds:**

- [x] - Dark Reaper PL incorrect. Should be 9PL for 4-5 models. #8023
- [x] - Shard of anaris relic cost should be 0 instead of 4. #8016 (And also the Firesabre too...)
- [x] - something, something, Vampire Hunter, something, blast keyword

**Harlequins:**

- [x] - "The Veil of Tears" has no profile

**Ynnari:**

- [x] - Warlord Validation #6498

- [x] - Stratagem: Exalted of Ynnead does not allow a second warlord trait to be selected. #6498 
- [x] - Drukhari
- [x] - Asuryani
- [x] - Harlequins

- [x] - Relic validation has not been checked. #6498
- [x] - Drukhari
- [x] - Asuryani
- [x] - Harlequins

- [x] - Ynnari keyword updates have not been QA'd. #6498
- [x] - Drukhari
- [x] - Asuryani
- [x] - Harlequins

- [x] - The Visarch does not generate Ynnari detachment rules for Craftworld Aeldari when taken as an HQ. (Posted by MarshalLaeroth) #6498
- [x] - Solitaire should not be available in Ynnari detachments. (Posted by MarshalLaeroth) #6498

**Comment by FarseerVeraenthis** [comment]
Thank you @DrTobogganMD !

**Comment by FarseerVeraenthis** [comment]
Let's see how long this takes... I mean, how bad can it be...?!?!?

**Comment by FarseerVeraenthis** [comment]
I'm going to throw this over the fence, the more I dig the more issues I find.
It will take time to resolve everything, but I'll do my best to get it done in a reasonable period of time.
Add new Issues here once the Ynnari update is released.
