### ISSUE TITLE
TRACKER: 0 765 020.M3 Datasheet/FAQ Update Tracker

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#8256]
- [ ] Black Templars - FAQ Cat changes done, Lib changes (WLTs, storm bolter cost for Crusaders) and new unit links TO DO
- [x] Blood Angels
- [x] Dark Angels - need to cover off the bugs, but it's mostly functional :+1:
- [x] Deathwatch
- [x] Space Wolves - useable enough for the week and a half before the supplement drops
- [x] Adepta Sororitas
- [x] Adeptus Custodes
- [x] Adeptus Mechanicus
- [x] Astra Militarum
- [x] PA: Blood of Baal - No changes
- [x] Chaos Knights
- [x] Chaos Space Marines
- [x] Craftworlds
- [x] Death Guard
- [x] Drukhari
- [x] PA: Engine War
- [x] PA: Faith and Fury - No changes
- [x] Genestealer Cults
- [x] Grey Knights
- [x] Harlequins
- [ ] Imperial Fists - FAQ Cat changes done, Lib changes (discipline, WLTs, SIW) and new unit links TO DO
- [ ] Iron Hands - FAQ Cat changes done, Lib changes (discipline) and new unit links TO DO
- [x] Imperial Knights
- [x] PA: Pariah
- [ ] Raven Guard -FAQ Cat changes done except "Death From Above" for Shrike, Lib changes (discipline, SIW) and new unit links TO DO
- [x] PA: Ritual of the Damned - No changes
- [x] PA: Saga of the Beast - No changes
- [ ] Salamanders - FAQ Cat changes done, Lib changes (discipline, SIW) and new unit links TO DO
- [x] T'au Empire
- [x] PA: The Greater Good
- [x] Thousand Sons
- [ ] Ultramarines - FAQ Cat changes done, Lib changes (discipline, SIW, Honour Guard, Quietus, Infernus) and new unit links TO DO
- [x] PA: War of the Spider
- [ ] White Scars - FAQ Cat changes done, Lib changes (discipline, SIW, Khan's Spear) and new unit links TO DO
- [x] Necrons
