### ISSUE TITLE
Blood Angels - Initial QA pass

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8367]
**File/Catalogue:** Blood Angels v189

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** 

- [x] Ancient in Terminator Armour is listed under Uncategorised instead of Elites
- [x] Librarian Dreadnought has a WS characteristic of 2+, but it should be 3+
- [x] Librarian Dreadnought has an A characteristic of 3, but it should be 4
- [x] Lemartes has an A characteristic of 5, but it should be 4
- [x] Sanguinary Guard has an A characteristic of 2, but it should be 3
- [x] Death Company Dreadnought has a M characteristic of 8”, but should be 6”
- [x] Death Company Dreadnought has an A characteristic of 4, but should be 5
- [x] Death Company Marine has a W characteristic of 1, but should be 2
- [x] Death Company Intercessors are currently called “Intersessor w/ CCW” and “Intercessor”, but should be called “Death Company Intercessor”
- [x] Death Company Intercessors have a profile name of “Veteran Intercessor Sergeant” and “Intercessor”, but should be called “Death Company Intercessor”
- [x] Death Company Intercessors have an A characteristic of 4, but should be 3
- [x] Death Company Intercessors have a Ld characteristic of 9, but should be 7
- [x] Furioso Dreadnought has a M characteristic of 8”, but should be 6”
- [x] Angelus Boltgun currently has a Range of 12”, but should be 18”
- [x] Baal Predator’s Baal flamestorm cannon is currently called “flamestorm cannon”, but should be called ”Baal flamestorm cannon”
- [x] Baal flamestorm cannon currently has a Range of 12”, but should be 18”
- [x] Furioso Dreadnought’s is currently able to take a frag cannon, but this should be a heavy frag cannon
- [x] The Blood Crozius currently has a Damage characteristic of D3, but should be 2
- [x] Blood talons currently have the ability text, “You can re-roll failed hit and wound rolls for this weapon.”, but should instead be, “Each time an attack is made with this weapon, you can re-roll the wound roll.”
- [x] Dead Man's Hand currently has an AP characteristic of -2, but should be -3
- [x] Encarmine axe currently has a S characteristic of +1, but should be +2
- [x] Encarmine axe currently has a D characteristic of D3, but should be 2
- [x] Encarmine sword currently has a S characteristic of User, but should be +1
- [x] Encarmine sword currently has a D characteristic of D3, but should be 2
- [x] The Executioner’s Axe currently has a D characteristic of D3, but should be 3
- [x] The Executioner’s Axe currently has the ability text, “Each time you roll a wound roll of 6+ for this weapon it causes 3 damage instead of D3.”, but should be “-“
- [x] Furioso fist currently has the ability text, “If a model is equipped with two Furioso fists, you can re-roll failed hit rolls when attacking with them.”, but should be “-“
- [x] Heaven's Teeth currently has an AP characteristic of -1, but should be -2
- [x] Death Company Dreadnought is currently 9 PL, but should be 7 PL
- [x] Death Company Marines with 6+ models taking Jump Packs currently costs +1 PL, but should be +2 PL
- [x] Furioso Dreadnought currently costs 8 PL, but should be 7 PL
- [x] Multiple units can take Death Masks, but no such wargear option exists anymore for:
- Sanguinary Guard
- Sanguinary Ancient
- [x] Death Company Marines are unable to take hand flamers, inferno pistols, or plasma pistols
- [x] Death Company Marines are unable to take power axes, power fists, power mauls, or power swords
- [x] Death Company Intercessors currently have a single model as default, but should have a minimum of 5 models
- [x] When taking different non-jump pack wargear options for a Sanguinary Priest, the unit is not flagged as [Legends]
- [x] Death Company Intercessors currently 22 points (Intersessor w/ CCW) or 20 points (Intercessor), but should be 24 points
- [x] Sanguinary Ancient’s power fist currently costs 5 points, but should be 0 points
- [x] Baal Predator’s storm bolter is currently 0 points, but should be 5 points
- [x] Baal Predator’s Baal flamestorm cannon is currently 25 points, but should be 0 points
- [x] Baal Predator’s twin assault cannon is currently 40 points, but should be 10 points
