### ISSUE TITLE
BA bug report consolidation

### ISSUE THREAD

**Issue by alphalas** [BSData/wh40k-9e#8515]
- [x] Heavy Bolters/Heavy Flamers on the Baal Predator should be 15 each for a total of 30 points not 20.
- [x] Invader ATV squad is completely missing from the catalogue
- [x] Still the issue of the Chief Librarian upgrade not allowing you to know a 3rd psychic power, still gives the error "has 1 too many selections from Disciplines (maximum 2)) on any Librarian even with the Chief Librarian upgrade selected
- [x] Death Company Marine default loadout is "bolt pistol and chainsword" but it should be an Astartes chainsword instead of chainsword
- [x] This is minor but on Sanguinary Guard data sheet, the angelus boltgun range is 1"8 instead of 18"
- [x] Brother Corbulo is missing the "Chief Apothecary" keyword
- [x] Technically the Librarian Dreadnought can have the Chief Librarian upgrade since he has the "Librarian" keyword
- [x] I think you can add the ability to be able to make a successor chapter, like in all the other Space Marine catalogues since right now all there is when you click on "Chapter Selection" is Forge World chapters. There is an entire section in Index Astartes: Blood Angels dedicated to running a successor chapter of your choosing, not jsut Flesh Tearers or Lamenters.
- [x] Also minor, but Chief Librarian Mephiston (Primaris)'s chief librarian key word is combined with the Mephiston keyword, should be separate.
- [x] Sanguinary Priest with jump pack should have 12" movement, currently remains at 6" 
- [x] Blood Angels still have the old codex's "Armoury of Baal" stratagem for extra relics. They should use "Relic of the Chapter" like the other Chapters.
- [x] Would also like to note that under Blood Angels, the Captain options seem to not be able to select the "Angel Artifice" relic when selected as Chapter Master (tested with the Captain with Master-crafted Heavy Bolt Rifle, and briefly looked at the basic Captain option, not sure if its true for other Captain options in Blood Angels/ Space Marines)
- [x] To add to primaris lieutenant wargear errors, the 1 neo-volkite pistol, master crafter power sword and storm shield option should add 1 PL as well as the 15 points for the pistol.
- [x] Chaplain still had Invocation of Destruction, five Death Company with Jump Packs should be Power Level 8 (there is still a +1 modifier to the Power Level in the Data Editor), and Furioso Dreadnought should be Power Level 8. 
- [x] To add to the DC marines PL with jump packs, when you increase the unit size to 6+, the PL for jump packs jumps to 4, should be 2 per BA index.
- [x] The Sanguinary Priest Option for Blood Angels is missing the “Hero of the Chapter” ability, which all characters should have.
- [x] Death Company should be max 10 in the squad. #8520 
- [x] Sanguinary Guard/Ancient weapon profiles need to be updated #8522 
- [x] Innovation of Destruction is no longer a valid Litany #8554 
- [x] Firestrike Servo Turret is missing from the selection list #8594 
- [x] Devastator HB should cost 15.
- [x] Death Company Intercessor melee/pistol models are misspelled as "Intersessor"
- [x] Also the Chapter Master Relic and Warlord trait are completely missing
- [x] Librarian Dreadnought should also be able to get Hero of the Chapter to take a warlord trait as it is a character.
- [ ] Blood Angels exclusive units seem to display the old Bolter Discipline rules. (Seen on Librarian Dreadnought, The Sanguinor an Captain Tycho. Untested on others) xml replace 9106-b297-021a-4d72 with 01a4-bec8-b573-fde7
- [x] Choosing Dante as a warlord doesn't seem to give the 1 bonus CP it is supposed to.
- [x] The Primaris Techmarine is missing every relic including the Master of the Forge one even with there being a warlord

**Comment by RespectableJack** [comment]
Also the Chapter Master Relic and Warlord trait are completely missing

**Comment by khinzaw** [comment]
Librarian Dreadnought should also be able to get Hero of the Chapter to take a warlord trait as it is a character.

**Comment by SashaOrlov** [comment]
Blood Angels exclusive units seem to display the old Bolter Discipline rules. (Seen on Librarian Dreadnought, The Sanguinor an Captain Tycho. Untested on others)
![image](https://user-images.githubusercontent.com/50091004/97792154-76ebfc00-1c15-11eb-9146-ede8c407f423.png)

**Comment by warpwookie** [comment]
The Primaris Apothecary is missing from the space wolves lists

**Comment by khinzaw** [comment]
Choosing Dante as a warlord doesn't seem to give the 1 bonus CP it is supposed to.

**Comment by RespectableJack** [comment]
The Primaris Techmarine is missing every relic including the Master of the Forge one even with there being a warlord

**Comment by RespectableJack** [comment]
In the IOS app version you can only take one heavy bolter variant on a 10 man Heavy Intercessor squad even though at 10 they get two

**Comment by alphalas** [comment]
@RespectableJack that last one needs to be reported separately as it’s a LibSM issue
