### ISSUE TITLE
Dark Angels - All-In-One Issue Tracker

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k-9e#8587]
I will attempt to list all issues here;

- [x] #8586 - Interrogator Chaplain in Terminator armor Master of Sanctity no option for warlord trait Wise Orator

- [x] #8581 - Ravenwing Ancient should be able to be the Chapter Ancient

- [x] #8555 - Interrogator Chaplain unable to take special wargear

- [x] #8551 - Dark Angels unable to select Successor Chapter Tactics

- [x] #8536 - Dark Angels Terminator Squad Heavy Weapons
1. Confusing selection routine, especially for Cyclone, Thunder Hammer, Storm Bolter Options. - Yeah, this needs a proper re-work...
2. Missing option of Cyclone and Pair of Lightning Claws?

- [x] #8534 Terminator Sergeant only has 2w not 3

- [x] #8472 WLT, Relic and nephilim issues
1. Warlord traits Brilliant Strategist: the description is wrong. - It looks OK to me, what is wrong?
2. Terminator sergeant: can’t use power fist + Storm Bolter, only three default choices. - Deathwing Terminator Sergeant has no access to a Power Fist.
3. Raven wing Talonmaster: unable to take relic Corvus Occulus. Setting was maximum relic = 0 - Check there is a Warlord selected
4. Nephilim fighter : strafing run ability is no more - now deleted, thanks!
5. Nephilim fighter : Can carry 2 black sword missile - it has two as standard and cannot replace them. this is already represented in the data.

- [x] #8479 Contemptor Dreadnought Cost

- [x] #8466 Various Dark Angels chapter command units cannot take the associated warlord traits

**Comment by FarseerVeraenthis** [comment]
OK, Deathwatch Terminator weapon selection is not totally friendly or elegant but it is functional 👍

**Comment by shrykm** [comment]
Deathwing Terminators aren't listed with the core keyword
