### ISSUE TITLE
0 856 020.M03 FAQ Tracker

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#8727]
- [x] Codex Supplement: Ultramarines
- [x] Codex: Necrons
- [x] Codex: Space Marines
- [x] Index Astartes: Black Templars
- [x] Index Astartes: Dark Angels
- [x] FW Legends: Space Marines
- [x] FW Legends: Astra Militarum
- [x] FW Legends: Adepta Sororitas
- [x] FW Legends: Inquisition
- [x] FW Legends: CSM
- [x] FW Legends: Death Guard
- [x] FW Legends: Chaos Daemons
- [x] FW Legends: R&H
- [x] FW Legends: Necrons
- [x] FW Legends: Orks
- [x] FW Legends: Aeldari 
- [x] FW Legends: T'au
