### ISSUE TITLE
FW Legends - QA Tracker

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#8846]
- [x] FW Legends: Space Marines
- [x] FW Legends: Astra Militarum
- [x] FW Legends: Adepta Sororitas
- [x] FW Legends: Inquisition
- [x] FW Legends: CSM
- [x] FW Legends: Death Guard
- [x] FW Legends: Chaos Daemons
- [x] FW Legends: R&H
- [x] FW Legends: Necrons
- [x] FW Legends: Orks
- [x] FW Legends: Aeldari
- [x] FW Legends: T'au

**Comment by grumblefoot** [comment]
Grey Knights forge-world legends options for dreadnought are missing from the current release.  There is also a duplication of the lascannon option for both vet and regular dreadnoughts. 

version 9.1.9  - this may be fixed now


from the FW legends PDF
DREADNOUGHT
This datasheet gains the following wargear options:
• This model’s assault cannon, storm bolter and Dreadnought combat weapon can be replaced with one of the following:
○ 1 heavy psycannon, 1 storm bolter, 1 Nemesis doomglaive (+15 pts).
○ 1 heavy psycannon, 1 incinerator, 1 Nemesis doomglaive (+25 pts).
