### ISSUE TITLE
0 850 1217.M3 FAQ Update Tracker

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#9045]
- [x] Codex Supplement: Deathwatch @Technoblazed 
- [x] Codex Supplement: Space Wolves @Mad-Spy 
- [x] Imperial Armour Compendium - T'au @Technoblazed 
- [x] Imperial Armour Compendium - Adeptus Astartes @acebaur 
- [x] Imperial Armour Compendium - Sanctic Astartes (GK) @tekton 
- [x] Imperial Armour Compendium - Chaos Daemons/CSM/Knights @Mad-Spy 
- [x] Imperial Armour Compendium - AM @Technoblazed 
- [x] Imperial Armour Compendium - Imperial Knights @DrTobogganMD 
- [x] Imperial Armour Compendium - Aeldari @FarseerVeraenthis 
- [x] Imperial Armour Compendium - Necrons @DrTobogganMD 
- [x] Imperial Armour Compendium - Orks @Technoblazed 
- [x] Imperial Armour Compendium - Tyranids @GenWilhelm 
- [x] Legends - Tauros Venators - Multi lasers
- [x] Legends - Sky Talon Keywords
- [x] Legends - Chimera autocannon wargear @Technoblazed 
- [x] Legends - Death Korps Grenadier Squad, Heavy flamer/heavy stubber points @Technoblazed 
- [x] Legends - Quartermaster Cadre Points/Force Org @Technoblazed 
- [x] Legends - Centaur Light Carrier points options @Technoblazed 
- [x] Legends - Zhufor The Impalor keywords
- [x] Legends - Renegade Cultists/Regenade Mutant Rabble, minions of Chaos rule.
- [x] Legends - Tomb Citadel - "Scaleable" spelling
- [x] Legends - Grot-guided bomm damage @Technoblazed 
- [x] Legends - Chinork - Open-topped rule
- [x] Legends - Just the entire deffrolla profile honestly @Technoblazed 

Legends Diff: https://www.diffchecker.com/6Qbt0Ts9
