### ISSUE TITLE
0 017 021.M03 - FAQ BONANZA 

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#9173]
- [x] Chaos Daemons - No relevant rules changes
- [x] Genestealer Cults  - No relevant rules changes
- [x] Harlequins
- [x] Necrons
- [x] Space Marines
- [x] T'au Empire
- [x] Tyranids
- [x] PA: Engine War - Adeptus Mechanicus
- [x] PA: Phoenix Rising - Drukhari
- [x] PA: Ritual of the Damned - no relevant rules changes
- [x] PA: Saga of the Beast - appears to have just removed Wolves rulings.
- [x] PA: The Greater Good - T'au
- [x] PA: War of the Spider - no relevant rule changes
- [x] CS: Blood Angels
- [x] Valerian and Aleya
