### ISSUE TITLE
MFM Points Costs - QA Tracker

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9183]
- [x] MFM - Space Marines
- [x] MFM - Ultramarines
- [x] MFM - White Scars
- [x] MFM - Iron Hands
- [x] MFM - Imperial Fists
- [x] MFM - Black Templars
- [x] MFM - Salamanders
- [x] MFM - Raven Guard
- [x] MFM - Blood Angels
- [x] MFM - Dark Angels
- [x] MFM - Space Wolves
- [x] MFM - Deathwatch
- [x] MFM - Grey Knights
- [x] MFM - Adepta Sororitas
- [x] MFM - Adeptus Custodes
- [x] MFM - Sisters of Silence
- [x] MFM - Officio Assassinorum
- [x] MFM - Astra Militarum
- [x] MFM - Adeptus Mechanicus
- [x] MFM - Imperial Knights
- [x] MFM - Inquisition
- [x] MFM - Chaos Space Marines
~~MFM - Death Guard~~ _Supplemented by Codex_
- [x] MFM - Thousand Sons
- [x] MFM - Chaos Daemons
- [x] MFM - Chaos Knights
- [x] MFM - Craftworlds
- [x] MFM - Drukhari
- [x] MFM - Harlequins
- [x] MFM - Ynnari
- [x] MFM - Necrons
- [x] MFM - Orks
- [x] MFM - T’au Empire
- [x] MFM - Tyranids
- [x] MFM - Genestealer Cults
- [x] MFM - Unaligned Fortifications
- [x] MFM - FW Space Marines
- [x] MFM - FW Grey Knights
- [x] MFM - FW Astra Militarum
- [x] MFM - FW Inquisition
- [x] MFM - FW Adeptus Custodes
- [x] MFM - FW Adeptus Mechanicus
- [x] MFM - FW Imperial Knights
- [x] MFM - Titan Legions
- [x] MFM - FW Chaos Space Marines
- [x] MFM - FW Death Guard
- [x] MFM - FW Chaos Daemons
- [x] MFM - FW Chaos Knights
- [x] MFM - Chaos Titan Legions
- [x] MFM - FW Craftworlds
- [x] MFM - FW Drukhari
- [x] MFM - FW Necrons
- [x] MFM - FW Orks
- [x] MFM - FW T’au Empire
- [x] MFM - FW Tyranids
- [x] MFM - Miscellaneous
