### ISSUE TITLE
Power Rating Update 2021 - QA Tracker

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k-9e#9184]
- [x] PL - Adepta Sororitas
- [x] PL - Adeptus Mechanicus
- [x] PL - Agents of the Imperium
- [x] PL - Astra Militarum
- [x] PL - Chaos Daemons
- [x] PL - Chaos Knights
- [x] PL - Chaos Space Marines
- [x] PL - Craftworlds
~~PL - Death Guard~~ _Supplemented by Codex_
- [x] PL - Drukhari
- [x] PL - Genestealer Cults
- [x] PL - Grey Knights
- [x] PL - Harlequins & Ynnari
- [x] PL - Imperial Knights
- [x] PL - Miscellaneous
- [x] PL - Necrons
- [x] PL - Orks
- [x] PL - Space Marines Supplement - Imperial Fists
- [x] PL - Space Marines Supplement - Iron Hands
- [x] PL - Space Marines Supplement - Raven Guard
- [x] PL - Space Marines Supplement - Salamanders
- [x] PL - Space Marines Supplement - Ultramarines
- [x] PL - Space Marines Supplement - White Scars
- [x] PL - T’au Empire
- [x] PL - Talons of the Emperor
- [x] PL - Thousand Sons
- [x] PL - Tyranids
- [x] PL - Unaligned Fortifications
