### ISSUE TITLE
TRACKER: Primary Catalogue Refactor

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#9757]
Tracker to track the use of `primary catalogue` constraints in catalogues.

TODO:
- [ ] Add Deathwatch chapter selector
- [ ] Add Black Templars chapter selector
- [ ] Remove instances of primary catalogue from the SM cat
