### ISSUE TITLE
Admech Codex When?

### ISSUE THREAD

**Issue by WindstormSCR** [BSData/wh40k-9e#9863]
Insert some appropriate bait here.

Release date is 5/29/21, it will NOT be released before then.

- [x] Force Rules Check
- [x] Forge World Dogma Check
- [x] Forge World Traits Check
- [x] Forge World Relics Check
- [x] Holy Orders Check
- [x] List Building Stratagems Check
- [x] Forge World HQ Check
- [x] Forge World Troop Check
- [x] Forge World Fast Attack Check
- [x] Forge World Elite Check
- [x] Forge World Heavy Support Check
- [x] Forge World Flyer Check
- [x] Forge World Transport Check
- [x] Update Points
- [x] Remove old data
- [x] Spell check
- [x] Q/A Pass

**Comment by Thairne** [comment]
merged
