### ISSUE TITLE
0 413 021.M03 - FAQ BONANZA

### ISSUE THREAD

**Issue by Technoblazed** [BSData/wh40k-9e#9933]
- [x] Core Book
- [x] PA Pariah
- [x] PA FAF
- [x] PA BoB
- [x] Thousand Sons
- [x] Space Marines
- [x] Necrons
- [x] Quins
- [x] Drukhari
- [x] Death Guard
- [x] Craftworlds
- [x] CSM
- [x] Ultramarines
- [x] Iron Hands
- [x] PA PR
- [x] Piety and Pain
- [x] PA:WotS - Chaos changes made
- [x] IA:C SPACE MARINES
- [x] IA:C KRIEG
- [x] IA:C ADMECH
- [x] IA:C Chaos
- [x] IA:C Drukhari
- [x] IA:C T'au
